// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.20;

/**
 * ============================================================================
 * BitVMX COMPATIBILITY MANUAL VERIFICATION TOOL
 * ============================================================================
 *
 * NOTE: This is NOT part of the regular test suite. This file exists as a
 * manual tool for verifying that transactions generated by BitVMX can pass
 * validation in the smart contracts.
 *
 * Regular test coverage exists in PeginManager.t.sol. This file is specifically
 * for one-off verification when coordinating with BitVMX implementations.
 *
 * ============================================================================
 * HOW TO USE:
 * ============================================================================
 *
 * STEP 1: Run BitVMX Accept Pegin Example
 * -----------------------------------------
 * In the BitVMX client repository:
 * In the file commons.rs, set the DEBUG_TX flag to true
 * Then run the accept_pegin example:
 *   ./examples/union/scripts/run-example.sh accept_pegin
 *
 * STEP 2: Extract Data from BitVMX Logs
 * --------------------------------------
 * From the output log, extract:
 *
 * COMMITTEE AGGREGATED PUBLIC KEY (33 bytes compressed):
 *   - Example: 0x031bda579ffbf5dcea00edf476d34334bb4f6b5fa4bd418ccf61244ef575bda31b
 *
 * MEMBER DISPUTE KEYS:
 *   compressed covenantKey:
 *     - publicKeyX: bytes32 (x-coordinate)
 *
 * SOLIDITY SYNTAXED REQUES PEGIN TRANSACTION:
 *   - The example should print the transaction structure in Solidity syntax
 *
 * ACCEPT PEGIN TXID:
 *   - The txid should be printed by the example
 *
 * STEP 3: Update Test Data Below
 * -------------------------------
 * Replace the placeholder values in the test function with the actual data extracted from BitVMX logs.
 *
 * covenantKeys[0,1,2,3]
 * committeeAggregatedKey
 * expectedAcceptPeginTxid
 * inside the _getBitVMXRequestPeginTransaction() function paste the complete transaction structure
 *
 * STEP 4: Run Test
 * ----------------
 *   forge clean && forge test --match-test test_bitVMXTransactionPassesValidation
 *
 * EXPECTED RESULT:
 * - Test should pass = BitVMX transactions are valid and compatible with contracts
 * - Test failure = Transaction structure mismatch, debug :)
 *
 * Known issues:
 * - The user btc address that is extracted from the OP_RETURN output can come from BITVMX as either even or odd,
 *   the contracts expect the pubkey even (prefix 0x02).
 *   This effectively means that the test will fail if the generated pubkey is odd (prefix 0x03).
 *   To make sure everything is working as expected we can modify the BtcHelper.pubKeyXonlyToCompact
 *   function temporarily to return 0x03 prefix instead of 0x02, and re-run the test to confirm it passes.
 *   Another temporary fix is to modify the receive_key in the user_1.yaml to be an even key.
 *
 *   Future fix should be either in BitVMX to always generate with 0x02 prefix, or to modify the transaction structure to get the uncompressed pubkey.
 *
 * ============================================================================
 */
import {Test} from "forge-std/Test.sol";
import {HelperContract} from "test/helpers/HelperContract.sol";
import {BtcTransaction, BtcTxIn, BtcTxOut} from "src/interfaces/IBitcoinManager.sol";
import {BtcTxSPVProof} from "src/interfaces/IPegCommonTypes.sol";
import {Role, Committee} from "src/interfaces/ICommitteeRegistry.sol";
import {StreamDenomination} from "src/interfaces/IStreamManager.sol";

contract BitVMXCompatibilityTest is Test, HelperContract {
    uint8 constant BITVMX_OP_COUNT = 2;
    uint8 constant BITVMX_WT_COUNT = 2;

    /**
     * @dev Verifies that a transaction generated by BitVMX passes contract validation.
     */
    function test_bitVMXTransactionPassesValidation() external {
        // ====================================================================
        // DATA FROM BitVMX - UPDATE THESE after running the request_pegin example in BitVMX client
        // ====================================================================

        // Covenant keys from BitVMX (x-coordinates only) - UPDATE THIS from BitVMX output
        bytes32[] memory covenantKeys = new bytes32[](4);
        covenantKeys[0] = 0x0ec6b8e5787e7146ee61585f00d2b49cd191b30deba8a744754c60589119239c;
        covenantKeys[1] = 0x47000231143a7ecabfc9d96c4177e6a374f9f90cdd81cbebcb70c9088f8a033a;
        covenantKeys[2] = 0xcc1d15954cd9c9a8e9f0a04224420ee14b0b8729d4dc933f2dd97b3af29b0ab4;
        covenantKeys[3] = 0xb0e42bec591549fb11880740f49978a35e95462482ebcda489a3fe119c937df3;

        // Committee aggregated key - UPDATE THIS from BitVMX output
        bytes memory committeeAggregatedKey = hex"030c260ce7e763ceece44830a886d8dd2c328445ffbcfd83c652bbc7671a55666e";

        // Accept Pegin TXID from BitVMX - UPDATE THIS from BitVMX output
        bytes32 expectedAcceptPeginTxid = hex"81d1062020bc78ca2a87ec2606d8bbcecdf5407120196e2d0f80a01ab98e7caa";

        // BitVMX transaction structure - UPDATE THIS from BitVMX output
        BtcTransaction memory requestPeginTx = _getBitVMXRequestPeginTransaction();

        // ====================================================================
        // TEST EXECUTION - DO NOT MODIFY BELOW
        // ====================================================================

        runTestDeployScript();
        registry.setMinCommitteeWatchtowersHarness(BITVMX_OP_COUNT);
        registry.setMinCommitteeOperatorsHarness(BITVMX_WT_COUNT);

        // Create a committee with test keys, then override with BitVMX keys
        _setupBitVMXCommittee(committeeAggregatedKey, covenantKeys);

        // Create SPV proof (mock for testing)
        bridgeMock.setBtcTransactionConfirmations(10);
        BtcTxSPVProof memory proof = createBtcTxSPVProof(requestPeginTx);

        // Call production validation - should NOT revert
        peginManager.requestPegin(proof);

        bytes32 requestPeginTxid = bitcoinManager.getBtcTxid(proof.btcTx);
        bytes32 acceptPeginTxid = peginManager.getAcceptPegin(requestPeginTxid);
        assertEq(acceptPeginTxid, expectedAcceptPeginTxid, "Accept Pegin TXID mismatch");
    }

    /**
     * @dev Creates a committee for stream 0 (0.001 BTC = 100,000 satoshis).
     * @return committeeId The created committee ID
     */
    function _setupCommitteeForStream0() internal returns (uint128) {
        // Register members for stream 0 (0.001 BTC)
        StreamDenomination denomination = StreamDenomination._0_001BTC;

        // Match BitVMX committee structure
        uint256 numOperators = BITVMX_OP_COUNT;
        uint256 numWatchtowers = BITVMX_WT_COUNT;
        uint256 totalMembers = numOperators + numWatchtowers;

        // Set the committee member count to 4 instead of default 10 (requires owner privileges)
        vm.prank(registry.owner());
        registry.setCommitteeMemberCount(totalMembers);

        vm.warp(10);
        vm.roll(10);
        setup_registerNewMembers(numWatchtowers, numOperators, denomination);

        // Get the committee ID from the registry (generated as keccak256(streamId, blockNumber))
        uint64 streamId = uint64(denomination);
        uint128 committeeId = registry.getPendingCommitteeId(streamId);

        // Complete the committee by depositing aggregated keys (7 members)
        setup_depositAggregatedKey_MultipleMembers(committeeId, 0, totalMembers);

        return committeeId;
    }

    /**
     * @dev Sets up a committee and overrides operator covenant and committee id keys with BitVMX values.
     * @param committeeAggregatedKey The aggregated public key from BitVMX
     * @param bitvmxCovenantKeys Array of covenant keys from BitVMX (x-coordinates only)
     * @return committeeId The created committee ID
     */
    function _setupBitVMXCommittee(bytes memory committeeAggregatedKey, bytes32[] memory bitvmxCovenantKeys)
        internal
        returns (uint128)
    {
        // Create a committee for stream 0 (0.001 BTC = 100,000 satoshis) to match BitVMX transaction
        uint128 committeeId = _setupCommitteeForStream0();

        // Override the committee's aggregated key with BitVMX's key
        // Stream ID = 0 (0.001 BTC stream), Packet Number = 0 (first packet)
        streamManager.setCommitteeAggregatedKeyHarness(0, 0, committeeAggregatedKey);

        // Get the committee info to find operator addresses
        Committee memory committee = registry.getCommittee(committeeId);

        // Expecting bitvmxCovenantKeys.length >= 4: first 2 -> operators, next 2 -> watchtowers
        uint256 opAssigned = 0;
        uint256 wtAssigned = 0;

        for (uint256 i = 0; i < committee.members.length; i++) {
            if (opAssigned < BITVMX_OP_COUNT && committee.members[i].role == Role.OPERATOR) {
                address operatorAddress = committee.members[i].memberAddress;
                memberRegistry.setMemberCovenantKeyHarness(operatorAddress, bitvmxCovenantKeys[opAssigned]);
                opAssigned++;
                continue;
            }

            if (wtAssigned < BITVMX_WT_COUNT && committee.members[i].role == Role.WATCHTOWER) {
                address wtAddress = committee.members[i].memberAddress;
                // watchtower keys are expected after operator keys in the array
                memberRegistry.setMemberCovenantKeyHarness(wtAddress, bitvmxCovenantKeys[BITVMX_OP_COUNT + wtAssigned]);
                wtAssigned++;
                continue;
            }

            if (opAssigned >= BITVMX_OP_COUNT && wtAssigned >= BITVMX_WT_COUNT) {
                break;
            }
        }

        // Recalculate the packet's enabler scriptPubKey with the updated BitVMX keys
        // This is necessary because the packet was created with default keys, but we've now
        // overridden both the committee aggregated key and the covenant keys.
        bytes32[] memory updatedDisputeKeys = registry.getCommitteeDisputeKeys(committeeId);
        bytes memory updatedEnablerScript =
            bitcoinManager.getEnablerOutputP2TRScriptPub(committeeAggregatedKey, updatedDisputeKeys);
        streamManager.setPacketEnablerScriptHarness(0, 0, updatedEnablerScript);

        return committeeId;
    }

    /**
     * @dev Returns the BitVMX transaction structure from the latest run.
     * This transaction should be copied as is from the bitvmx logs after running the accept_pegin example.
     */
    function _getBitVMXRequestPeginTransaction() internal pure returns (BtcTransaction memory) {
        BtcTxIn[] memory inputs = new BtcTxIn[](1);
        inputs[0] = BtcTxIn({
            txId: 0xce159afe2f77222fbba52cbbb5aafecfe301db05e7f914d849f1733dcd515261,
            vout: 0,
            scriptSig: hex"",
            sequence: 4294967293
        });

        BtcTxOut[] memory outputs = new BtcTxOut[](3);
        outputs[0] = BtcTxOut({
            amount: 100000,
            scriptPubKey: hex"51200b317878279ab6af9d1af7b74a54d89d5ad6b48a05759ff5c1e242b6fac9fa06"
        });

        outputs[1] = BtcTxOut({
            amount: 0,
            scriptPubKey: hex"6a4552534b5f504547494e00000000000000007ac5496aee77c1ba1f0854206a26dda82a81d6d8a5a32f1e36335d6c3233bb36c4c5cdb51153a1698399ea0691be6e01a8580573"
        });

        outputs[2] = BtcTxOut({
            amount: 1080,
            scriptPubKey: hex"5120a00556469858b54b0a230c3277c2eaa5f181ef36360ff261b620f4bb928c756f"
        });

        return BtcTransaction({version: 2, inputs: inputs, outputs: outputs, locktime: 0});
    }
}
