// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.20;

/**
 * ============================================================================
 * BitVMX COMPATIBILITY MANUAL VERIFICATION TOOL
 * ============================================================================
 *
 * NOTE: This is NOT part of the regular test suite. This file exists as a
 * manual tool for verifying that transactions generated by BitVMX can pass
 * validation in the smart contracts.
 *
 * Regular test coverage exists in PeginManager.t.sol. This file is specifically
 * for one-off verification when coordinating with BitVMX implementations.
 *
 * ============================================================================
 * HOW TO USE:
 * ============================================================================
 *
 * STEP 1: Run BitVMX Request Pegin Example
 * -----------------------------------------
 * In the BitVMX client repository:
 * In the file commons.rs, set the DEBUG_TX flag to true
 * Then run the request_pegin example:
 *   ./examples/union/scripts/run-example.sh request_pegin
 *
 * STEP 2: Extract Data from BitVMX Logs
 * --------------------------------------
 * From the output log, extract:
 *
 * COMMITTEE AGGREGATED PUBLIC KEY (33 bytes compressed):
 *   - Example: 0x031bda579ffbf5dcea00edf476d34334bb4f6b5fa4bd418ccf61244ef575bda31b
 *
 * MEMBER DISPUTE KEYS:
 *   compressed covenantKey:
 *     - publicKeyX: bytes32 (x-coordinate)
 *
 * SOLIDITY SYNTAXED TRANSACTION:
 *   - The example should print the transaction structure in Solidity syntax
 *
 * STEP 3: Update Test Data Below
 * -------------------------------
 * Replace the placeholder values in the test function with the actual data
 * extracted from BitVMX logs.
 * covenantKeys[0,1,2,3]
 * committeeAggregatedKey
 * inside the _getBitVMXTransaction() function paste the complete transaction structure
 *
 * STEP 4: Run Test
 * ----------------
 *   forge clean && forge test --match-test test_bitVMXTransactionPassesValidation -vv
 *
 * EXPECTED RESULT:
 * - Test should pass = BitVMX transaction is valid and compatible with contracts
 * - Test failure = Transaction structure mismatch, debug :)
 *
 * ============================================================================
 */
import {Test} from "forge-std/Test.sol";
import {HelperContract} from "test/helpers/HelperContract.sol";
import {BtcTransaction, BtcTxIn, BtcTxOut} from "src/interfaces/IBitcoinManager.sol";
import {BtcTxEncoder} from "src/libraries/BtcTxEncoder.sol";
import {BtcTxSPVProof} from "src/interfaces/IPegCommonTypes.sol";
import {
    MemberRegistrationKeys,
    ECDSAPublicKey,
    RSAPublicKey,
    Role,
    UTXO,
    Committee
} from "src/interfaces/ICommitteeRegistry.sol";
import {StreamDenomination, Stream} from "src/interfaces/IStreamManager.sol";
import "forge-std/console.sol";

contract BitVMXCompatibility is Test, HelperContract {
    /**
     * @dev Verifies that a transaction generated by BitVMX passes contract validation.
     */
    function test_bitVMXTransactionPassesValidation() external {
        // ====================================================================
        // DATA FROM BitVMX - UPDATE THESE after running the request_pegin example in BitVMX client
        // ====================================================================

        // Covenant keys from BitVMX (x-coordinates only)
        bytes32[] memory covenantKeys = new bytes32[](4);
        covenantKeys[0] = 0x25d60e69c1a604170e75d9551ecd9cf5e8358d88c851b123783c775c3a3457b3; // UPDATE from BitVMX
        covenantKeys[1] = 0x62a0614ef05cb9bd9d2abbb45f94639a77b8ad9833d4946da7157e8c10614778; // UPDATE from BitVMX
        covenantKeys[2] = 0xe353f9d8769b18daf46ff4d6fb525b60416e5ada37676183a62feff8f2825787; // UPDATE from BitVMX
        covenantKeys[3] = 0x24f8209e35a50738e4bf7be2df24502282367c599b1ba3412d57420bce304be3; // UPDATE from BitVMX

        // Committee aggregated key - UPDATE THIS from BitVMX output
        bytes memory committeeAggregatedKey = hex"02172fc9b06d592811f6dcc4dbd0d075ea92003e25c28b64cbaa291c81d2db0a54";

        // BitVMX transaction structure - UPDATE THIS from BitVMX output
        BtcTransaction memory requestPeginTx = _getBitVMXTransaction();

        // ====================================================================
        // TEST EXECUTION - DO NOT MODIFY BELOW
        // ====================================================================

        runTestDeployScript();
        registry.setMinCommitteeWatchtowersHarness(2);
        registry.setMinCommitteeOperatorsHarness(2);

        // Create a committee with test keys, then override with BitVMX keys
        _setupBitVMXCommittee(committeeAggregatedKey, covenantKeys);

        // Create SPV proof (mock for testing)
        bridgeMock.setBtcTransactionConfirmations(10);
        BtcTxSPVProof memory proof = createBtcTxSPVProof(requestPeginTx);

        // Call production validation - should NOT revert
        peginManager.requestPegin(proof);
    }

    /**
     * @dev Creates a committee for stream 0 (0.001 BTC = 100,000 satoshis).
     * @return committeeId The created committee ID
     */
    function _setupCommitteeForStream0() internal returns (uint128) {
        // Register members for stream 0 (0.001 BTC)
        StreamDenomination denomination = StreamDenomination._0_001BTC;

        // Match BitVMX committee structure: 4 operators only, no watchtowers
        // This ensures the enabler output uses exactly the 4 operator covenant keys
        uint256 numOperators = 2; // Matches BitVMX operator count
        uint256 numWatchtowers = 2; // BitVMX example has no watchtowers
        uint256 totalMembers = 4; // Only operators

        // Set the committee member count to 4 instead of default 10 (requires owner privileges)
        vm.prank(registry.owner());
        registry.setCommitteeMemberCount(totalMembers);

        vm.warp(10);
        vm.roll(10);
        setup_registerNewMembers(numWatchtowers, numOperators, denomination);

        // Get the committee ID from the registry (generated as keccak256(streamId, blockNumber))
        uint64 streamId = uint64(denomination);
        uint128 committeeId = registry.getPendingCommitteeId(streamId);

        // Complete the committee by depositing aggregated keys (7 members)
        setup_depositAggregatedKey_MultipleMembers(committeeId, 0, totalMembers);

        return committeeId;
    }

    /**
     * @dev Sets up a committee and overrides operator covenant keys with BitVMX values.
     * @param committeeAggregatedKey The aggregated public key from BitVMX
     * @param bitvmxCovenantKeys Array of covenant keys from BitVMX (x-coordinates only)
     * @return committeeId The created committee ID
     */
    function _setupBitVMXCommittee(bytes memory committeeAggregatedKey, bytes32[] memory bitvmxCovenantKeys)
        internal
        returns (uint128)
    {
        // Create a committee for stream 0 (0.001 BTC = 100,000 satoshis) to match BitVMX transaction
        uint128 committeeId = _setupCommitteeForStream0();

        // Override the committee's aggregated key with BitVMX's key
        // Stream ID = 0 (0.001 BTC stream), Packet Number = 0 (first packet)
        streamManager.setCommitteeAggregatedKeyHarness(0, 0, committeeAggregatedKey);

        // Get the committee info to find operator addresses
        Committee memory committee = registry.getCommittee(committeeId);

        // Expecting bitvmxCovenantKeys.length >= 4: first 2 -> operators, next 2 -> watchtowers
        uint256 operatorsToAssign = 2;
        uint256 watchtowersToAssign = 2;
        uint256 opAssigned = 0;
        uint256 wtAssigned = 0;

        for (uint256 i = 0; i < committee.members.length; i++) {
            if (opAssigned < operatorsToAssign && committee.members[i].role == Role.OPERATOR) {
                address operatorAddress = committee.members[i].memberAddress;
                memberRegistry.setMemberCovenantKeyHarness(operatorAddress, bitvmxCovenantKeys[opAssigned]);
                opAssigned++;
                continue;
            }

            if (wtAssigned < watchtowersToAssign && committee.members[i].role == Role.WATCHTOWER) {
                address wtAddress = committee.members[i].memberAddress;
                // watchtower keys are expected after operator keys in the array
                memberRegistry.setMemberCovenantKeyHarness(
                    wtAddress, bitvmxCovenantKeys[operatorsToAssign + wtAssigned]
                );
                wtAssigned++;
                continue;
            }

            if (opAssigned >= operatorsToAssign && wtAssigned >= watchtowersToAssign) {
                break;
            }
        }

        return committeeId;
    }

    /**
     * @dev Returns the BitVMX transaction structure from the latest run.
     * This transaction should be copied as is from the bitvmx logs after running the request_pegin example.
     */
    function _getBitVMXTransaction() internal pure returns (BtcTransaction memory) {
        BtcTxIn[] memory inputs = new BtcTxIn[](1);
        inputs[0] = BtcTxIn({
            txId: 0x757600a6561e7e59dc5d921e1ff1fdd9fac492edf170a9757def9413893914ef,
            vout: 0,
            scriptSig: hex"",
            sequence: 4294967293
        });

        BtcTxOut[] memory outputs = new BtcTxOut[](3);
        outputs[0] = BtcTxOut({
            amount: 100000,
            scriptPubKey: hex"51204df70d5b1b475714b7f25882a582c0f1c44217dd8da5b647f98765f54d6125b5"
        });

        outputs[1] = BtcTxOut({
            amount: 0,
            scriptPubKey: hex"6a4552534b5f504547494e00000000000000007ac5496aee77c1ba1f0854206a26dda82a81d6d8e728aa9022e7554cb553be119dc225a66490a5c3384b2351c966aaefbd0d8b82"
        });

        outputs[2] = BtcTxOut({
            amount: 1080,
            scriptPubKey: hex"5120379dd85099f00556ffb8a3de5cdce5a20d6a80fa00840f7c19417a69a40dd6f9"
        });

        return BtcTransaction({version: 2, inputs: inputs, outputs: outputs, locktime: 0});
    }
}
