// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.20;

/**
 * ============================================================================
 * BitVMX COMPATIBILITY MANUAL VERIFICATION TOOL
 * ============================================================================
 *
 * NOTE: This is NOT part of the regular test suite. This file exists as a
 * manual tool for verifying that transactions generated by BitVMX can pass
 * validation in the smart contracts.
 *
 * Regular test coverage exists in PeginManager.t.sol. This file is specifically
 * for one-off verification when coordinating with BitVMX implementations.
 *
 * ============================================================================
 * HOW TO USE:
 * ============================================================================
 *
 * STEP 1: Run BitVMX Accept Pegin Example
 * -----------------------------------------
 * In the BitVMX client repository:
 * In the file commons.rs, set the DEBUG_TX flag to true
 * Then run the accept_pegin example:
 *   ./examples/union/scripts/run-example.sh accept_pegin
 *
 * STEP 2: Extract Data from BitVMX Logs
 * --------------------------------------
 * From the output log, extract:
 *
 * COMMITTEE AGGREGATED PUBLIC KEY (33 bytes compressed):
 *   - Example: 0x031bda579ffbf5dcea00edf476d34334bb4f6b5fa4bd418ccf61244ef575bda31b
 *
 * MEMBER DISPUTE KEYS:
 *   compressed disputeKey:
 *     - publicKeyX: bytes32 (x-coordinate)
 *
 * SOLIDITY SYNTAXED REQUES PEGIN TRANSACTION:
 *   - The example should print the transaction structure in Solidity syntax
 *
 * ACCEPT PEGIN TXID:
 *   - The txid should be printed by the example
 *
 * STEP 3: Update Test Data Below
 * -------------------------------
 * Replace the placeholder values in the test function with the actual data extracted from BitVMX logs.
 *
 * disputeKeys[0,1,2,3]
 * committeeAggregatedKey
 * expectedAcceptPeginTxid
 * inside the _getBitVMXRequestPeginTransaction() function paste the complete transaction structure
 *
 * STEP 4: Run Test
 * ----------------
 *   forge clean && forge test --match-test test_bitVMXTransactionPassesValidation
 *
 * EXPECTED RESULT:
 * - Test should pass = BitVMX transactions are valid and compatible with contracts
 * - Test failure = Transaction structure mismatch, debug :)
 *
 * ============================================================================
 * ADVANCE_FUNDS_TX COMPATIBILITY TEST
 * ============================================================================
 *
 * The test_bitVMXAdvanceFundsTxSPVPassesValidation test validates that the
 * ADVANCE_FUNDS_TX SPV from BitVMX (rust-bitvmx-client) passes contract validation.
 *
 * HOW TO GET THE SPV FROM BITVMX:
 * 1. Run: ./examples/union/scripts/run-example.sh advance_funds
 * 2. In the logs, find "ADVANCE_FUNDS_TX SPV for unit test" (printed after "Advance funds complete")
 *    NOTE: There are TWO SPVs with this label - use the one from "Advance funds complete"
 *    (NOT the one from "Pegin accepted and confirmed" which is the ACCEPT_PEGIN_TX)
 * 3. Map the parameters to BtcTxSPVProof struct:
 *    - block_hash -> blockHash
 *    - tx_hex -> decode into BtcTransaction (excluding witness for txid calc)
 *    - merkle_branch_path -> merkleBranchPath
 *    - merkle_branch_hashes -> merkleBranchHashes (convert to bytes32[])
 *
 * REFERENCE TX_HEX (source for _getBitVMXAdvanceFundsTransaction - from bitvmx logs:
 * 02000000000101340acc8ed678f2c031a6232ef564433d18e2876ed06530552313f611f19570010200000000fdffffff03e681010000000000160014bcf0470d714b9a4d5559c883d94dc18709ee199d0000000000000000226a20000000000000000000000000000000000000000000000000000000000000000022470000000000001600147160086956f4dc826a89fc010f33bd86bf5347ed02483045022100a5d5b068a4ad0877fe2aad780a63a22539604ee7c99cb6e58507ca96c3251b3402201840ebde4546a29b780107ca96cfa03d3c961f95fe61b8f717bf34575c15edc50121034ae05c8530a41ef79d0e95200d69dae62bc1f491a306ee434413f7dc2857764300000000
 *
 * ============================================================================
 *
 * Known issues:
 * - The user btc address that is extracted from the OP_RETURN output can come from BITVMX as either even or odd,
 *   the contracts assume the user's pubkey is even (prefix 0x02) as a protocol-level decision.
 *   This effectively means that the test will fail if the generated pubkey is odd (prefix 0x03).
 *   A temporary fix is to modify the receive_key in the user_1.yaml to be an even key.
 *
 *   Future fix should be either in BitVMX to always generate with 0x02 prefix, or to modify the transaction structure to get the uncompressed pubkey.
 *
 * ============================================================================
 */
import {Test} from "forge-std/Test.sol";
import {HelperContract} from "test/helpers/HelperContract.sol";
import {
    BtcTransaction, BtcTxIn, BtcTxOut, PrevoutData, BitcoinSignatureData
} from "src/interfaces/IBitcoinManager.sol";
import {BtcTxSPVProof, StreamPosition} from "src/interfaces/IPegCommonTypes.sol";
import {Role, Committee} from "src/interfaces/ICommitteeRegistry.sol";
import {CompactPubKey} from "src/interfaces/IMemberRegistry.sol";
import {Stream, Slot, StreamDenomination, PegStatus} from "src/interfaces/IStreamManager.sol";
import {BtcScriptParser} from "src/libraries/BtcScriptParser.sol";
import {Constants} from "src/libraries/Constants.sol";
import {BtcHelper} from "src/libraries/BtcHelper.sol";
import {OperatorTakeInfo} from "src/interfaces/IOperatorTakeManager.sol";

contract BitVMXCompatibilityTest is Test, HelperContract {
    uint8 constant BITVMX_OP_COUNT = 2;
    uint8 constant BITVMX_WT_COUNT = 2;

    /**
     * @dev Verifies that a transaction generated by BitVMX passes contract validation.
     */
    function test_bitVMXTransactionPassesValidation() external {
        // ====================================================================
        // DATA FROM BitVMX - UPDATE THESE after running the request_pegin example in BitVMX client
        // ====================================================================

        // Dispute keys from BitVMX (33-byte compressed: parity + x-coordinate) - UPDATE THIS from BitVMX output
        CompactPubKey[] memory disputeKeys = new CompactPubKey[](4);
        disputeKeys[0] =
            CompactPubKey({parity: 0x02, xOnly: 0x0ec6b8e5787e7146ee61585f00d2b49cd191b30deba8a744754c60589119239c});
        disputeKeys[1] =
            CompactPubKey({parity: 0x02, xOnly: 0x47000231143a7ecabfc9d96c4177e6a374f9f90cdd81cbebcb70c9088f8a033a});
        disputeKeys[2] =
            CompactPubKey({parity: 0x02, xOnly: 0xcc1d15954cd9c9a8e9f0a04224420ee14b0b8729d4dc933f2dd97b3af29b0ab4});
        disputeKeys[3] =
            CompactPubKey({parity: 0x02, xOnly: 0xb0e42bec591549fb11880740f49978a35e95462482ebcda489a3fe119c937df3});

        // Committee aggregated key - UPDATE THIS from BitVMX output
        bytes memory committeeAggregatedKey = hex"030c260ce7e763ceece44830a886d8dd2c328445ffbcfd83c652bbc7671a55666e";

        // Accept Pegin TXID from BitVMX - UPDATE THIS from BitVMX output
        bytes32 expectedAcceptPeginTxid = hex"81d1062020bc78ca2a87ec2606d8bbcecdf5407120196e2d0f80a01ab98e7caa";

        // BitVMX transaction structure - UPDATE THIS from BitVMX output
        BtcTransaction memory requestPeginTx = _getBitVMXRequestPeginTransaction();

        // ====================================================================
        // TEST EXECUTION - DO NOT MODIFY BELOW
        // ====================================================================

        runTestDeployScript();
        registry.setMinCommitteeWatchtowersHarness(BITVMX_OP_COUNT);
        registry.setMinCommitteeOperatorsHarness(BITVMX_WT_COUNT);

        // Create a committee with test keys, then override with BitVMX keys
        _setupBitVMXCommittee(committeeAggregatedKey, disputeKeys);

        // Create SPV proof (mock for testing)
        bridgeMock.setBtcTransactionConfirmations(10);
        BtcTxSPVProof memory proof = createBtcTxSPVProof(requestPeginTx);

        // Call production validation - should NOT revert
        peginManager.requestPegin(proof);

        bytes32 requestPeginTxid = bitcoinManager.getBtcTxid(proof.btcTx);
        bytes32 acceptPeginTxid = peginManager.getAcceptPegin(requestPeginTxid);
        assertEq(acceptPeginTxid, expectedAcceptPeginTxid, "Accept Pegin TXID mismatch");
    }

    /**
     * @dev Creates a committee for stream 0 (0.001 BTC = 100,000 satoshis).
     * @return committeeId The created committee ID
     */
    function _setupCommitteeForStream0() internal returns (uint128) {
        // Register members for stream 0 (0.001 BTC)
        StreamDenomination denomination = StreamDenomination._0_001BTC;

        // Match BitVMX committee structure
        uint256 numOperators = BITVMX_OP_COUNT;
        uint256 numWatchtowers = BITVMX_WT_COUNT;
        uint256 totalMembers = numOperators + numWatchtowers;

        // Set the committee member count to 4 instead of default 10 (requires owner privileges)
        vm.prank(registry.owner());
        registry.setCommitteeMemberCount(totalMembers);

        vm.warp(10);
        vm.roll(10);
        setup_registerNewMembers(numWatchtowers, numOperators, denomination);

        // Get the committee ID from the registry (generated as keccak256(streamId, blockNumber))
        uint64 streamId = uint64(denomination);
        uint128 committeeId = registry.getPendingCommitteeId(streamId);

        // Complete the committee by depositing aggregated keys (7 members)
        setup_depositAggregatedKey_MultipleMembers(committeeId, 0, totalMembers);

        return committeeId;
    }

    /**
     * @dev Sets up a committee and overrides operator dispute and committee id keys with BitVMX values.
     * @param committeeAggregatedKey The aggregated public key from BitVMX
     * @param bitvmxDisputeKeys Array of dispute keys from BitVMX (33-byte compressed: parity + x-coordinate)
     * @return committeeId The created committee ID
     */
    function _setupBitVMXCommittee(bytes memory committeeAggregatedKey, CompactPubKey[] memory bitvmxDisputeKeys)
        internal
        returns (uint128)
    {
        // Create a committee for stream 0 (0.001 BTC = 100,000 satoshis) to match BitVMX transaction
        uint128 committeeId = _setupCommitteeForStream0();

        // Override the committee's take aggregated key with BitVMX's key
        registry.setCommitteeTakeAggregatedKeyHarness(committeeId, committeeAggregatedKey);

        // Get the committee info to find operator addresses
        Committee memory committee = registry.getCommittee(committeeId);

        // Expecting bitvmxDisputeKeys.length >= 4: first 2 -> operators, next 2 -> watchtowers
        uint256 opAssigned = 0;
        uint256 wtAssigned = 0;

        for (uint256 i = 0; i < committee.members.length; i++) {
            if (opAssigned < BITVMX_OP_COUNT && committee.members[i].role == Role.OPERATOR) {
                address operatorAddress = committee.members[i].memberAddress;
                memberRegistry.setMemberDisputeKeyHarness(operatorAddress, bitvmxDisputeKeys[opAssigned]);
                opAssigned++;
                continue;
            }

            if (wtAssigned < BITVMX_WT_COUNT && committee.members[i].role == Role.WATCHTOWER) {
                address wtAddress = committee.members[i].memberAddress;
                // watchtower keys are expected after operator keys in the array
                memberRegistry.setMemberDisputeKeyHarness(wtAddress, bitvmxDisputeKeys[BITVMX_OP_COUNT + wtAssigned]);
                wtAssigned++;
                continue;
            }

            if (opAssigned >= BITVMX_OP_COUNT && wtAssigned >= BITVMX_WT_COUNT) {
                break;
            }
        }

        // Recalculate the packet's enabler scriptPubKey with the updated BitVMX keys
        // This is necessary because the packet was created with default keys, but we've now
        // overridden both the committee aggregated key and the dispute keys.
        CompactPubKey[] memory updatedDisputeKeys = registry.getCommitteeDisputeKeys(committeeId);
        bytes memory updatedEnablerScript =
            bitcoinManager.getEnablerOutputP2TRScriptPub(committeeAggregatedKey, updatedDisputeKeys);
        streamManager.setPacketEnablerScriptHarness(0, 0, updatedEnablerScript);

        return committeeId;
    }

    /**
     * @dev Returns the BitVMX transaction structure from the latest run.
     * This transaction should be copied as is from the bitvmx logs after running the accept_pegin example.
     */
    function _getBitVMXRequestPeginTransaction() internal pure returns (BtcTransaction memory) {
        BtcTxIn[] memory inputs = new BtcTxIn[](1);
        inputs[0] = BtcTxIn({
            txId: 0xce159afe2f77222fbba52cbbb5aafecfe301db05e7f914d849f1733dcd515261,
            vout: 0,
            scriptSig: hex"",
            sequence: 4294967293
        });

        BtcTxOut[] memory outputs = new BtcTxOut[](3);
        outputs[0] = BtcTxOut({
            amount: 100000,
            scriptPubKey: hex"51200b317878279ab6af9d1af7b74a54d89d5ad6b48a05759ff5c1e242b6fac9fa06"
        });

        outputs[1] = BtcTxOut({
            amount: 0,
            scriptPubKey: hex"6a4552534b5f504547494e00000000000000007ac5496aee77c1ba1f0854206a26dda82a81d6d8a5a32f1e36335d6c3233bb36c4c5cdb51153a1698399ea0691be6e01a8580573"
        });

        outputs[2] = BtcTxOut({
            amount: 1080,
            scriptPubKey: hex"5120a00556469858b54b0a230c3277c2eaa5f181ef36360ff261b620f4bb928c756f"
        });

        return BtcTransaction({version: 2, inputs: inputs, outputs: outputs, locktime: 0});
    }

    /**
     * @dev Verifies that ADVANCE_FUNDS_TX SPV from BitVMX passes contract validation.
     * @dev Validates transaction structure and OP_RETURN pegout_id format compatibility.
     */
    function test_bitVMXAdvanceFundsTxSPVPassesValidation() external {
        runTestDeployScript();

        // Parse BitVMX ADVANCE_FUNDS_TX into BtcTransaction struct
        BtcTransaction memory advanceFundsTx = _getBitVMXAdvanceFundsTransaction();

        // Verify transaction structure
        assertEq(advanceFundsTx.version, 2, "Version should be 2");
        assertEq(advanceFundsTx.inputs.length, 1, "Should have 1 input");
        assertEq(advanceFundsTx.outputs.length, 3, "Should have 3 outputs (user, OP_RETURN, change)");
        assertEq(advanceFundsTx.locktime, 0, "Locktime should be 0");

        // Verify output 0: User funds (P2WPKH) - 100000 - (P2TR_FEE*2 + SPEED_UP) = 98790 for 0.001 BTC stream
        assertEq(
            advanceFundsTx.outputs[Constants.ADVANCE_FUNDS_VOUT_USER].amount,
            98_790,
            "User amount should be 98790 sats (0.001 BTC stream)"
        );
        assertEq(
            advanceFundsTx.outputs[Constants.ADVANCE_FUNDS_VOUT_USER].scriptPubKey.length,
            22,
            "User output should be P2WPKH (22 bytes)"
        );

        // Verify output 1: OP_RETURN with pegout_id (BitVMX format: 6a 20 <32 bytes>)
        assertEq(
            advanceFundsTx.outputs[Constants.ADVANCE_FUNDS_VOUT_OP_RETURN].amount, 0, "OP_RETURN amount should be 0"
        );
        bytes memory opReturnScript = advanceFundsTx.outputs[Constants.ADVANCE_FUNDS_VOUT_OP_RETURN].scriptPubKey;
        assertEq(opReturnScript.length, 34, "OP_RETURN should be 34 bytes (6a + 20 + 32)");

        // Verify our getPegoutIdScript produces matching format for bytes32(0)
        bytes memory expectedPegoutIdScript = BtcScriptParser.getPegoutIdScript(bytes32(0));
        assertEq(
            opReturnScript,
            expectedPegoutIdScript,
            "OP_RETURN format should match BtcScriptParser.getPegoutIdScript (BitVMX compatible)"
        );

        // Verify BitcoinManager accepts the pegout_id output format
        bitcoinManager.validatePegoutIdOutput(
            advanceFundsTx.outputs[Constants.ADVANCE_FUNDS_VOUT_OP_RETURN], bytes32(0)
        );

        // Verify output 2: Operator change (P2WPKH)
        assertEq(advanceFundsTx.outputs[2].amount, 18_210, "Operator change should be 18210 sats");

        // Verify txid can be computed (transaction encoding is valid)
        bytes32 txid = bitcoinManager.getBtcTxid(advanceFundsTx);
        assertTrue(txid != bytes32(0), "Txid should be non-zero");
    }

    /// @dev Input txid from BitVMX ADVANCE_FUNDS_TX (wire format - will be reversed during encoding)
    bytes32 constant BITVMX_ADVANCE_FUNDS_INPUT_TXID =
        0x340acc8ed678f2c031a6232ef564433d18e2876ed06530552313f611f1957001;

    /**
     * @dev Parses the BitVMX ADVANCE_FUNDS_TX hex into BtcTransaction struct.
     * @dev Witness data is excluded as it's not needed for txid calculation.
     */
    function _getBitVMXAdvanceFundsTransaction() internal pure returns (BtcTransaction memory) {
        BtcTxIn[] memory inputs = new BtcTxIn[](1);
        inputs[0] = BtcTxIn({txId: BITVMX_ADVANCE_FUNDS_INPUT_TXID, vout: 2, scriptSig: hex"", sequence: 4294967293});

        BtcTxOut[] memory outputs = new BtcTxOut[](3);
        outputs[0] = BtcTxOut({
            amount: 98_790, // 100000 - (P2TR_FEE*2 + SPEED_UP) for 0.001 BTC stream
            scriptPubKey: hex"0014bcf0470d714b9a4d5559c883d94dc18709ee199d"
        });
        outputs[1] = BtcTxOut({
            amount: 0,
            scriptPubKey: hex"6a200000000000000000000000000000000000000000000000000000000000000000"
        });
        outputs[2] = BtcTxOut({amount: 18_210, scriptPubKey: hex"00147160086956f4dc826a89fc010f33bd86bf5347ed"});

        return BtcTransaction({version: 2, inputs: inputs, outputs: outputs, locktime: 0});
    }

    /// @dev BitVMX user pubkey (P2WPKH bcf0470d714b9a4d5559c883d94dc18709ee199d) from bitvmx logs
    bytes constant BITVMX_USER_PUBKEY = hex"03e728aa9022e7554cb553be119dc225a66490a5c3384b2351c966aaefbd0d8b82";

    /// @dev BitVMX ADVANCE_FUNDS_TX SPV from bitvmx logs (use the one from "Advance funds complete")
    bytes32 constant BITVMX_ADVANCE_FUNDS_BLOCK_HASH =
        0x635a99891a2f778961a16b568f844977f1837afbad3bca062ef631f0e4f4f7e4;
    uint256 constant BITVMX_ADVANCE_FUNDS_MERKLE_PATH = 1;
    bytes32 constant BITVMX_ADVANCE_FUNDS_MERKLE_HASH =
        0xaaf0b60c9bb76bae3b59bfdcd9e08f7556858895a6d8765fa0b97e0a6f29c5fc;

    /**
     * @dev Calls registerAdvanceFunds with the ACTUAL BitVMX ADVANCE_FUNDS_TX SPV end-to-end.
     * @dev Uses real SPV data from bitvmx logs; stream 0 (0.001 BTC); BitVMX user pubkey.
     * @dev Uses OperatorTakeManagerHarness to inject pegoutId=0 since BitVMX produces it.
     */
    function test_registerAdvanceFundsWithBitVMXSPV() external {
        runTestDeployScript();
        registry.setMinCommitteeWatchtowersHarness(BITVMX_OP_COUNT);
        registry.setMinCommitteeOperatorsHarness(BITVMX_WT_COUNT);

        // BitVMX committee keys (from test_bitVMXTransactionPassesValidation)
        CompactPubKey[] memory disputeKeys = new CompactPubKey[](4);
        disputeKeys[0] =
            CompactPubKey({parity: 0x02, xOnly: 0x0ec6b8e5787e7146ee61585f00d2b49cd191b30deba8a744754c60589119239c});
        disputeKeys[1] =
            CompactPubKey({parity: 0x02, xOnly: 0x47000231143a7ecabfc9d96c4177e6a374f9f90cdd81cbebcb70c9088f8a033a});
        disputeKeys[2] =
            CompactPubKey({parity: 0x02, xOnly: 0xcc1d15954cd9c9a8e9f0a04224420ee14b0b8729d4dc933f2dd97b3af29b0ab4});
        disputeKeys[3] =
            CompactPubKey({parity: 0x02, xOnly: 0xb0e42bec591549fb11880740f49978a35e95462482ebcda489a3fe119c937df3});
        bytes memory committeeAggregatedKey = hex"030c260ce7e763ceece44830a886d8dd2c328445ffbcfd83c652bbc7671a55666e";

        uint128 committeeId = _setupBitVMXCommittee(committeeAggregatedKey, disputeKeys);
        bridgeMock.setBtcTransactionConfirmations(10);

        // Request pegin with BitVMX request tx (stream 0)
        BtcTransaction memory requestTx = _getBitVMXRequestPeginTransaction();
        bridgeMock.setBtcBlockchainBestChainHeight(BEST_CHAIN_HEIGHT);
        peginManager.requestPegin(createBtcTxSPVProof(requestTx));
        Stream memory str0 = streamManager.getStream(100_000);
        bridgeMock.setBtcBlockchainBestChainHeight(
            BEST_CHAIN_HEIGHT + int256(uint256(str0.timelockSettings.requestPeginTimelock))
        );

        // Accept pegin for stream 0 - use contract's expected accept tx (getAcceptPeginSignatureHash)
        BtcTransaction memory acceptTx = _getAcceptPeginTxMatchingContract(requestTx, 0);
        bridgeMock.setBtcBlockchainBestChainHeight(BEST_CHAIN_HEIGHT);
        bridgeMock.setBtcTransactionConfirmations(CONFIRMATIONS);
        peginManager.acceptPegin(createBtcTxSPVProof(acceptTx));
        bridgeMock.setBtcBlockchainBestChainHeight(BEST_CHAIN_HEIGHT + 1);
        bytes32 acceptPeginTxid = bitcoinManager.getBtcTxid(acceptTx);
        setup_addOperatorTakeTxidsForStream_MultipleOperators(acceptPeginTxid, committeeId, 0, 0, 4, 100_000);

        // Pegout flow for stream 0 with BitVMX user
        RegisterUserTakeSetup memory setup = _setupPegoutForStream0(acceptPeginTxid, acceptTx);

        // Trigger operator take, cancel user take
        vm.warp(block.timestamp + TAKE_0_TIMEOUT_DEFAULT + 1);
        // Use operator indices (2,3) for 4-member committee - indices 3,4 would use vm.addr(5) which is NOT in committee
        setup_addMemberSignature_MultipleMembers(setup.pegoutTxid, registry.committeeMemberCount() / 2, 2);
        operatorTakeManager.triggerOperatorTake(setup.acceptPeginTxid);
        OperatorTakeInfo memory opInfo = operatorTakeManager.getOperatorTakeInfo(setup.acceptPeginTxid);
        address operatorAddress = opInfo.operatorTakeAddress;

        setup.cancelUserTakeSPV = createBtcTxSPVProof(
            createCancelUserTakeTx(
                setup.acceptPeginTxid,
                BtcHelper.compactPubKeyToBytes(memberRegistry.getMemberDisputePubKey(operatorAddress))
            )
        );

        // Set pegout id to 0 for BitVMX compatibility, otherwise would fail with IncorrectOutputScript.
        operatorTakeManager.setOperatorTakePegoutIdHarness(setup.acceptPeginTxid, bytes32(0));

        // Build advance funds SPV with ACTUAL BitVMX tx and SPV data from bitvmx logs
        bytes32[] memory merkleHashes = new bytes32[](1);
        merkleHashes[0] = BITVMX_ADVANCE_FUNDS_MERKLE_HASH;
        setup.advanceFundsSPV = createBtcTxSPVProof(
            _getBitVMXAdvanceFundsTransaction(),
            BITVMX_ADVANCE_FUNDS_BLOCK_HASH,
            BITVMX_ADVANCE_FUNDS_MERKLE_PATH,
            merkleHashes
        );

        bridgeMock.setBtcBlockchainBestChainHeight(BEST_CHAIN_HEIGHT + 20); // Ensure cancel block < advance block
        operatorTakeManager.registerCancelUserTake(setup.cancelUserTakeSPV);

        vm.prank(operatorAddress);
        operatorTakeManager.registerAdvanceFunds(setup.acceptPeginTxid, setup.advanceFundsSPV);

        StreamPosition memory pos = streamManager.getStreamPosition(setup.acceptPeginTxid);
        assertEq(uint256(pos.pegStatus), uint256(PegStatus.ADVANCED), "Peg status should be ADVANCED");
    }

    /// @dev Builds accept pegin tx that exactly matches what the contract expects (from getAcceptPeginSignatureHash)
    function _getAcceptPeginTxMatchingContract(BtcTransaction memory _requestTx, uint64 _streamId)
        internal
        view
        returns (BtcTransaction memory)
    {
        (uint64 packetNumber,, bytes32 btcReimbursementPubKey) =
            bitcoinManager.getPeginOpReturnData(_requestTx.outputs[Constants.REQUEST_PEGIN_VOUT_OP_RETURN]);
        uint128 committeeId = streamManager.getCommitteeId(_streamId, packetNumber);
        bytes memory committeePubKey = registry.getCommitteeTakePubKey(committeeId);
        bytes memory enablerScriptPubKey = streamManager.getEnablerScriptPubKey(_streamId, packetNumber);
        bytes32 requestPeginTxid = bitcoinManager.getBtcTxid(_requestTx);

        PrevoutData[] memory prevoutDatas = new PrevoutData[](2);
        prevoutDatas[0] = PrevoutData({
            value: _requestTx.outputs[Constants.REQUEST_PEGIN_VOUT_TAPTREE].amount,
            scriptPubKey: _requestTx.outputs[Constants.REQUEST_PEGIN_VOUT_TAPTREE].scriptPubKey
        });
        prevoutDatas[1] = PrevoutData({value: Constants.SPEED_UP_AMOUNT, scriptPubKey: enablerScriptPubKey});

        CompactPubKey[] memory disputeKeys = registry.getCommitteeDisputeKeys(committeeId);
        BitcoinSignatureData memory sigData = bitcoinManager.getAcceptPeginSignatureHash(
            committeePubKey, btcReimbursementPubKey, requestPeginTxid, prevoutDatas, disputeKeys
        );
        return sigData.tx;
    }

    /// @dev Stream 0 pegout setup (0.001 BTC, BitVMX user)
    /// @dev Builds accept pegin tx matching exactly what the contract expects (from getAcceptPeginSignatureHash)
    /// @dev Builds accept pegin tx matching exactly what the contract expects (via getAcceptPeginSignatureHash)
    /// @dev Stream 0 pegout setup (0.001 BTC, BitVMX user)
    function _setupPegoutForStream0(bytes32 acceptPeginTxid, BtcTransaction memory acceptTx)
        internal
        returns (RegisterUserTakeSetup memory setup)
    {
        setup.acceptPeginTxid = acceptPeginTxid;
        setup.acceptPeginSPV = createBtcTxSPVProof(acceptTx);
        setup.stream = streamManager.getStream(100_000);
        setup.userPubKey = BITVMX_USER_PUBKEY;
        setup.packetNumber = 0;
        setup.slotId = 0;

        bridgeMock.setWeisTransferredToUnionBridge(BtcHelper.satoshiToWei(100_000));
        Slot memory slot = streamManager.getSlot(0, 0, 0);
        PrevoutData[] memory prevoutDatas = new PrevoutData[](2);
        prevoutDatas[0] = PrevoutData({value: slot.acceptPeginAmount, scriptPubKey: slot.scriptPubKey});
        prevoutDatas[1] =
            PrevoutData({value: Constants.ENABLER_AMOUNT, scriptPubKey: streamManager.getEnablerScriptPubKey(0, 0)});
        BitcoinSignatureData memory pegoutData =
            bitcoinManager.getPegoutTxData(setup.userPubKey, setup.acceptPeginTxid, prevoutDatas);
        setup.pegoutTx = pegoutData.tx;
        setup.pegoutTxSPVProof = createBtcTxSPVProof(setup.pegoutTx);
        setup.pegoutTxid = pegoutData.txid;
        setup.pegoutSignatureHash = pegoutData.signatureHash;

        vm.prank(globalUserAddress);
        pegoutManager.tryPegout{value: BtcHelper.satoshiToWei(100_000)}(setup.userPubKey);
        // Need nonces from all 4 members before addMemberSignature (AllNoncesAreNotPresent check)
        setup_addMemberNonce_MultipleMembers(setup.pegoutTxid, 0, registry.committeeMemberCount());
    }
}
