// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "forge-std/console.sol";
import {HelperContract} from "test/helpers/HelperContract.sol";
import {
    BtcTransaction,
    BtcTxSPVProof,
    StreamPosition,
    RequestPegInTempInfo,
    PegStatus,
    IPegManager
} from "src/interfaces/IPegManager.sol";
import {BtcTxIn, BtcTxOut} from "src/interfaces/IBitcoinManager.sol";
import {Slot, SlotState, Packet, Stream, IStreamManager} from "src/interfaces/IStreamManager.sol";
import {BTC_TRANSACTION_CONFIRMATION_INVALID_MERKLE_BRANCH_ERROR_CODE} from "src/interfaces/IBridge.sol";
import {ProofValidator} from "src/ProofValidator.sol";
import {BtcHelper} from "src/libraries/BtcHelper.sol";
import {Constants} from "src/libraries/Constants.sol";

// This addresses and pubkeys are the ones generated by anvil and the deploy script
bytes32 constant MEMBER_0_PUBKEY = 0xecffc8106b3c958bd88d6d30490b30363bf5adf16d35c5d31a2bd219df53ca52;
address constant MEMBER_0_ADDRESS = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
bytes32 constant MEMBER_1_PUBKEY = 0xefc3606f43ef541fff3328af5ea0a16ad9e4ae67d8d5595e8ba4ad1c00517d55;
address constant MEMBER_1_ADDRESS = 0x70997970C51812dc3A010C7d01b50e0d17dc79C8;
bytes32 constant MEMBER_2_PUBKEY = 0x1976ee2a061feb3976914ed2526369c7141b5490f48d5623485e833c2e9c5819;
address constant MEMBER_2_ADDRESS = 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC;

contract TestPegManager is Test, HelperContract {
    // Arrange
    // https://www.blockchain.com/explorer/blocks/btc/879500
    uint64 internal constant PACKET_NUMBER = 0;
    address internal constant RSK_DESTINATION_ADDRESS = 0x7Ac5496aee77c1bA1F0854206A26DdA82A81d6d8;

    // For more info about this see: https://book.getfoundry.sh/forge/writing-tests#before-test-setups
    function beforeTestSetup(bytes4 testSelector) public pure returns (bytes[] memory beforeTestCalldata) {
        if (
            testSelector == this.test_acceptPegInRequest_Success.selector
                || testSelector == this.test_acceptPegInRequest_Revert_AlreadyRegisteredAcceptPegIn.selector
                || testSelector == this.test_acceptPegInRequest_Revert_IncorrectInputsNumber.selector
                || testSelector == this.test_acceptPegInRequest_Revert_IncorrectOutputsNumber.selector
                || testSelector == this.test_acceptPegInRequest_Revert_InvalidVout.selector
                || testSelector == this.test_acceptPegInRequest_Revert_Revert_NotEnoughConfirmations.selector
        ) {
            beforeTestCalldata = new bytes[](1);
            beforeTestCalldata[0] = abi.encodePacked(this.test_registerPegInRequest_Success.selector);
        }
        if (testSelector == this.test_requestPegOut_fromAcceptPegIn_Success.selector) {
            beforeTestCalldata = new bytes[](2);
            beforeTestCalldata[0] = abi.encodePacked(this.test_registerPegInRequest_Success.selector);
            beforeTestCalldata[1] = abi.encodePacked(this.test_acceptPegInRequest_Success.selector);
        }
    }

    function setUp() external {
        runTestDeployScript();
    }

    function test_getTemporaryPegInAddress_Success() external view {
        address dummyRskAddress = 0x7Ac5496aee77c1bA1F0854206A26DdA82A81d6d8;
        // TODO this is the value that includes the op_return data inside the taptree
        // this should be put back once the protocol builder is updated
        // string memory tempAddress = "bcrt1ptp8gw3yt9rjavkrlxhwmlm9y5w4c5u6yeeltmupanle76eq4ftrszyjhnn";
        string memory tempAddress = "bcrt1py28js8ef0lgpe5mrh8yn7apt52tkc8k95cyrm8m4fjmpu5zn2mps7esu9h";

        string memory result = pm.getTemporaryPegInAddress(dummyRskAddress, VALUE, BTC_REIMBURSEMENT_PUBKEY);
        assertEq(result, tempAddress, "Incorrect temporary peg in address at PegManager");
    }

    // ========================== REGISTER PEG IN REQUEST ==========================
    function test_registerPegInRequest_Success() external {
        // Arrange
        BtcTransaction memory btcTransaction = getBtcPegInRequestTx();
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInRequestTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectEmit(address(pm));
        // We emit the event we expect to see.
        emit IPegManager.RegisteredPegInRequest(
            pegInRequestTxSPVProof.blockHash,
            getExpectedPegInRequestTxHash(),
            0,
            VALUE,
            PACKET_NUMBER,
            RSK_DESTINATION_ADDRESS,
            BTC_REIMBURSEMENT_PUBKEY,
            btcTransaction.outputs[0].scriptPubKey
        );

        // Act
        pm.registerPegInRequest(pegInRequestTxSPVProof);

        // Assert
        bytes32 txHash = getExpectedPegInRequestTxHash();
        // Registered Peg In
        StreamPosition memory streamPosition = pm.getPegInRequest(txHash);
        assertEq(streamPosition.streamId, 0, "Incorrect streamId registered");
        assertEq(streamPosition.packetNumber, 0, "Incorrect packetNumber registered");
        assertEq(uint256(streamPosition.pegStatus), uint256(PegStatus.REGISTERED), "PegIn Request was not registered");
        // Registered Peg In Temp info
        RequestPegInTempInfo memory pegInTempInfo = pm.getRequestPegInTempInfo(txHash);
        assertEq(pegInTempInfo.outputAmount, VALUE, "Incorrect peg in temp info value");
        assertEq(
            pegInTempInfo.rskDestinationAddress,
            RSK_DESTINATION_ADDRESS,
            "Incorrect peg in temp info destinationAddress"
        );
        assertEq(
            pegInTempInfo.btcReimbursementPubKey,
            BTC_REIMBURSEMENT_PUBKEY,
            "Incorrect peg in temp info btcReimbursementPubKey"
        );
        assertEq(
            pegInTempInfo.utxoScriptPubKey,
            btcTransaction.outputs[0].scriptPubKey,
            "Incorrect peg in temp info utxo script pub key"
        );
    }

    function test_registerPegInRequest_Revert_AlreadyRegistered() external {
        // Arrange
        BtcTransaction memory btcTransaction = getBtcPegInRequestTx();
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInRequestTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Register First Peg In Request
        pm.registerPegInRequest(pegInRequestTxSPVProof);

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(IPegManager.AlreadyRegisteredPegInRequest.selector, getExpectedPegInRequestTxHash())
        );

        // Act Register Second Peg In Request
        pm.registerPegInRequest(pegInRequestTxSPVProof);
    }

    function test_registerPegInRequest_Revert_NotEnoughConfirmations() external {
        // Arrange
        int256 actualConfirmations = 0;
        BtcTransaction memory btcTransaction = getBtcPegInRequestTx();
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(actualConfirmations);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInRequestTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        Stream memory stream = streamManager.getStream(VALUE);
        vm.expectRevert(
            abi.encodeWithSelector(
                ProofValidator.NotEnoughConfirmations.selector, actualConfirmations, stream.pegInConfirmations
            )
        );
        // Act
        pm.registerPegInRequest(pegInRequestTxSPVProof);
    }

    function test_registerPegInRequest_Revert_BridgeBtcTxInvalidMerkleBranch() external {
        // Arrange
        BtcTransaction memory btcTransaction = getBtcPegInRequestTx();
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(BTC_TRANSACTION_CONFIRMATION_INVALID_MERKLE_BRANCH_ERROR_CODE);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInRequestTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                ProofValidator.BridgeBtcTxInvalidMerkleBranch.selector,
                getExpectedPegInRequestTxHash(),
                pegInRequestTxSPVProof.merkleBranchPath,
                pegInRequestTxSPVProof.merkleBranchHashes
            )
        );
        // Act
        pm.registerPegInRequest(pegInRequestTxSPVProof);
    }

    function test_registerPegInRequest_Revert_IncorrectBtcTxVersion() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcPegInRequestTx();
        btcTransaction.version = 1;
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInRequestTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.InvalidBtcTxVersion.selector, btcTransaction.version, Constants.BTC_TX_VERSION
            )
        );

        // Act
        pm.registerPegInRequest(pegInRequestTxSPVProof);
    }

    function test_registerPegInRequest_Revert_IncorrectLocktime() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcPegInRequestTx();
        btcTransaction.locktime = 1;
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInRequestTxSPVProof = createBtcTxSPVProof(btcTransaction);
        pegInRequestTxSPVProof.merkleBranchHashes[0] =
            0x3fcef4a1ddf759a858190b89ecbd1ff3dffb49704e110b68baf5b5de7021910f;

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(IPegManager.InvalidLocktime.selector, btcTransaction.locktime, Constants.LOCKTIME)
        );

        // Act
        pm.registerPegInRequest(pegInRequestTxSPVProof);
    }

    // ========================== ACCEPT PEG IN ==========================
    function test_acceptPegInRequest_Revert_UnregisteredPegInRequest() external {
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx();
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(IPegManager.UnregisteredPegInRequest.selector, btcTransaction.inputs[0].txId)
        );

        // Act
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);
    }

    function test_acceptPegInRequest_Success() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx();
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectEmit(address(pm));

        // We emit the event we expect to see.
        bytes32 pegInRequestTxHash = pegInAcceptedTxSPVProof.btcTx.inputs[0].txId;
        bytes32 acceptPegInTxHash = getExpectedAcceptPegInTxHash();
        uint64 streamId = 0;
        uint64 slotId = 0;
        emit IPegManager.AcceptedPegInRequest(
            pegInAcceptedTxSPVProof.blockHash,
            acceptPegInTxHash,
            pegInRequestTxHash,
            0, //vout
            StreamPosition({
                streamId: streamId,
                packetNumber: PACKET_NUMBER,
                slotId: slotId,
                pegStatus: PegStatus.ACCEPTED
            }),
            BTC_REIMBURSEMENT_PUBKEY,
            RSK_DESTINATION_ADDRESS,
            satoshiToWei(btcTransaction.outputs[0].amount), // Rbtc amount
            btcTransaction.outputs[0].scriptPubKey
        );

        // Act
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);

        // Assert
        // Registered Peg In Stream Position
        StreamPosition memory streamPosition = pm.getPegInRequest(pegInRequestTxHash);
        assertEq(streamPosition.streamId, streamId, "Incorrect streamId registered");
        assertEq(streamPosition.packetNumber, PACKET_NUMBER, "Incorrect packetNumber registered");
        assertEq(streamPosition.slotId, 0, "Incorrect slotId registered");
        assertEq(uint256(streamPosition.pegStatus), uint256(PegStatus.ACCEPTED), "PegIn Request was not accepted");
        // Registered Peg In Temp info should be deleted
        RequestPegInTempInfo memory pegInTempInfo = pm.getRequestPegInTempInfo(pegInRequestTxHash);
        assertEq(pegInTempInfo.outputAmount, 0, "Peg in temp info outputAmount should be deleted");
        assertEq(
            pegInTempInfo.rskDestinationAddress, address(0), "Peg in temp info destinationAddress should be deleted"
        );
        assertEq(
            pegInTempInfo.btcReimbursementPubKey,
            bytes32(0),
            "Peg in temp info btcReimbursementPubKey should be deleted"
        );
        assertEq(pegInTempInfo.utxoScriptPubKey, hex"", "Peg in temp info utxoScriptPubKey should be deleted");
        // Registered Peg In Slot
        Slot memory slot = streamManager.getSlot(streamId, PACKET_NUMBER, slotId);
        assertEq(uint256(slot.state), uint256(SlotState.FILLED), "Slot should be filled");
        assertEq(slot.acceptPegInTx, acceptPegInTxHash, "Incorrect acceptPegInTx");
        assertEq(slot.acceptPegInAmount, btcTransaction.outputs[0].amount, "Incorrect acceptPegInAmount");
        assertEq(slot.scriptPubKey, btcTransaction.outputs[0].scriptPubKey, "Incorrect scriptPubKey");
    }

    function test_acceptPegInRequest_Revert_AlreadyRegisteredAcceptPegIn() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx();
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Register First  Accept Peg In Request
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(IPegManager.AlreadyRegisteredAcceptPegIn.selector, btcTransaction.inputs[0].txId)
        );

        // Act Register Second Accept Peg In Request
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);
    }

    function test_acceptPegInRequest_Revert_IncorrectBtcTxVersion() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx();
        btcTransaction.version = 1;
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.InvalidBtcTxVersion.selector, btcTransaction.version, Constants.BTC_TX_VERSION
            )
        );

        // Act
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);
    }

    function test_acceptPegInRequest_Revert_IncorrectLocktime() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx();
        btcTransaction.locktime = 1;
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(IPegManager.InvalidLocktime.selector, btcTransaction.locktime, Constants.LOCKTIME)
        );

        // Act
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);
    }

    function test_acceptPegInRequest_Revert_IncorrectSequence() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx();
        btcTransaction.inputs[0].sequence = 0;
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.InvalidSequence.selector, btcTransaction.inputs[0].sequence, Constants.SEQUENCE
            )
        );

        // Act
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);
    }

    function test_acceptPegInRequest_Revert_IncorrectInputsNumber() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx();
        btcTransaction.inputs = new BtcTxIn[](0);
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn accepted tx struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(IPegManager.IncorrectInputsNumber.selector, btcTransaction.inputs.length, 1)
        );

        // Act
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);
    }

    function test_acceptPegInRequest_Revert_IncorrectOutputsNumber() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx();
        btcTransaction.outputs = new BtcTxOut[](0);
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn accepted tx struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(IPegManager.IncorrectOutputsNumber.selector, btcTransaction.outputs.length, 2)
        );

        // Act
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);
    }

    function test_acceptPegInRequest_Revert_InvalidVout() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx();
        btcTransaction.inputs[0].vout = 1;
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn accepted tx struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Assert
        vm.expectRevert(abi.encodeWithSelector(IPegManager.InvalidVout.selector, btcTransaction.inputs[0].vout, 0));

        // Act
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);
    }

    function test_acceptPegInRequest_Revert_Revert_NotEnoughConfirmations() external {
        // ===  Before test setup  is run for this  test ===
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx();
        int256 actualConfirmations = 0;
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(actualConfirmations);
        // Create PegIn accepted tx struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);
        Stream memory stream = streamManager.getStreamById(0);
        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                ProofValidator.NotEnoughConfirmations.selector, actualConfirmations, stream.pegInConfirmations
            )
        );

        // Act
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);
    }

    // ================= Request PegOut =================
    function test_requestPegOut_Success() external {
        // Arrange
        bytes32 expectedHash = 0xf48100e48109fb0e00c7d4e826b0509347f64fd2874bca28cff17d3d31e8bb9a;
        bytes memory expectedDigest =
            hex"00010200000000000000234337e863e00e6ff45f167a14f3963bea912bc0d739c2b402d04f376e814ae2e247139cedddd1ee740814e7de2e771c3745091bbb7af21d4122087c8bc17a36a0c6dbc3091625a23fd870bf8d09182484c12fa63a5c29045a431cf445f153e523e9829bfb4e23fbd3c4848baa035af15d73bcb83e510f7f097f90a21a4280d2006bb47323a1d7550c68619b10ffa4748cae2dc9f58375cfb06ae22cc8020e530000000000";

        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";

        bytes32 txId = 0xb24858ade3e5be49ae63facb93524ddf460d0771f093525dae328b6c435516a2;
        bytes memory scriptPubKey = hex"02f519f51e435c20d38af683ea86862f4591ce8cda248077c2d9a72a76b62f32";

        uint64 amount = 10000000; // 0.1 BTC
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);

        Stream memory stream = streamManager.getStream(uint64(amount));
        uint64 packetNumber = 0;
        uint64 slotId = 0;

        streamManager.setSlotHarness(
            stream.streamId, packetNumber, slotId, SlotState.FILLED, scriptPubKey, txId, amount
        );

        // Assert
        vm.expectEmit(address(pm));
        emit IPegManager.PegOutRequested(
            usrPubKey, amount, expectedHash, expectedDigest, stream.streamId, packetNumber, slotId
        );

        // Act
        pm.requestPegOut{value: amountInWei}(usrPubKey);

        // Assert
        bytes32 pegOutSignatureHash = pm.getPegOutSignatureHash(stream.streamId, packetNumber, slotId);
        assertEq(pegOutSignatureHash, expectedHash, "expected hash doesn't match the pegout computed one");

        // Assert
        Slot memory slot = streamManager.getSlot(stream.streamId, packetNumber, slotId);
        assertEq(uint64(slot.state), uint64(SlotState.LOCKED), "Slot was not locked");

        // Assert
        // Check if the signatures struct was initialized by checking that the function doesn't revert, we expect false since it hasn't been signed yet
        assertEq(
            pm.checkAllSignaturesReady(expectedHash, stream.streamId, packetNumber, slotId),
            false,
            "Signatures struct hasn't been initialized"
        );
    }

    function test_requestPegOut_fromAcceptPegIn_Success() external {
        // Arrange
        bytes32 expectedHash = 0x99befc0d4167efaf7e3ec5e8067a1a7c3a90ec85c1f9a792ce309b7eca630999;
        bytes memory expectedDigest =
            hex"00010200000000000000cf72c080d473fbab8c45b1c13be4215e216bb20171c0fd659632ce0779df8bc7b223ac0e009cf54402b2529ea4312214616df58c903ec7fd399c12fb08e8e675be45ad9e08ae96e42d7fd1f70a454432049ebd6a625fa377ffa22033fd8692d623e9829bfb4e23fbd3c4848baa035af15d73bcb83e510f7f097f90a21a4280d2cca26f66149c86d9940e70592f0e9c8b07b8cb01d0aabb7782c9d6b17bc12e270000000000";

        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";

        uint64 amount = VALUE;
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);

        Stream memory stream = streamManager.getStream(uint64(amount));
        (Slot memory slot, uint64 packetNumber) = streamManager.getFirstFilledSlot(stream.streamId);

        // Assert
        vm.expectEmit(address(pm));
        emit IPegManager.PegOutRequested(
            usrPubKey, amount, expectedHash, expectedDigest, stream.streamId, packetNumber, slot.slotId
        );

        // Act
        pm.requestPegOut{value: amountInWei}(usrPubKey);

        // Assert
        bytes32 result = pm.getPegOutSignatureHash(stream.streamId, packetNumber, slot.slotId);
        assertEq(result, expectedHash, "expected hash doesn't match the pegout computed one");

        // Assert
        slot = streamManager.getSlot(stream.streamId, packetNumber, slot.slotId);
        assertEq(uint64(slot.state), uint64(SlotState.LOCKED), "Slot was not locked");
    }

    function test_requestPegOut_Revert_InvalidPublicKeyLength() external {
        // Arrange
        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b00";

        // Assert
        vm.expectRevert(abi.encodeWithSelector(IPegManager.InvalidPubKeyLength.selector, usrPubKey.length));

        // Act
        pm.requestPegOut(usrPubKey);
    }

    function test_requestPegOut_Revert_StreamNotFoundByDenomination() external {
        // Arrange
        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";
        uint64 amount = 5;
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);

        // Assert
        vm.expectRevert(abi.encodeWithSelector(IStreamManager.StreamNotFoundByDenomination.selector, amount));

        // Act
        pm.requestPegOut{value: amountInWei}(usrPubKey);
    }

    function test_requestPegOut_Revert_NoFilledSlot() external {
        // Arrange
        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";
        uint64 amount = 100000; // 0.1 BTC
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);

        Stream memory stream = streamManager.getStream(uint64(amount));
        uint64 packetNumber = 0;

        // Assert
        vm.expectRevert(abi.encodeWithSelector(IStreamManager.NoFilledSlot.selector, stream.streamId, packetNumber));

        // Act
        pm.requestPegOut{value: amountInWei}(usrPubKey);
    }

    // we only check the revert case since the success cases are being checked in the _addMemberSignaturePegoutTxHash tests
    function test_checkAllSignaturesReady_Revert_PegOutRequestNotFound() external {
        // Arrange
        bytes32 pegOutTxHash = 0x0000000000000000000000000000000000000000000000000000000000000001;
        uint64 streamId = 0;
        uint64 packetNumber = 0;
        uint64 slotId = 0;

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.PegOutRequestNotFound.selector, pegOutTxHash, streamId, packetNumber, slotId
            )
        );

        // Act
        pm.checkAllSignaturesReady(pegOutTxHash, streamId, packetNumber, slotId);
    }

    function test_addMemberSignaturePegoutTxHash_Success() external {
        // This test has to perform all the steps of the pegout flow but we do not need the asserts
        // since that is already being checked
        (bytes32 pegOutTxHash, uint64 streamId, uint64 packetNumber, uint64 slotId) = helper_arrangeRequestPegout();

        // Arrange
        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        // Assert
        // We emit the event we expect to see.
        bytes32 committeeMember0Pubkey = MEMBER_0_PUBKEY;
        vm.expectEmit(address(pm));
        emit IPegManager.SignatureAdded(
            pegOutTxHash, streamId, packetNumber, slotId, committeeMember0Pubkey, signature, nonce
        );

        // Act
        address committeeMember0adr = MEMBER_0_ADDRESS;
        vm.startPrank(committeeMember0adr);
        bool allSignaturesReady =
            pm.addMemberSignaturePegoutTxHash(pegOutTxHash, streamId, packetNumber, slotId, signature, nonce);
        vm.stopPrank();

        // Assert
        assertEq(allSignaturesReady, false, "Not all signatures should be ready at this point");

        // Assert
        // We emit the event we expect to see.
        bytes32 committeeMember1Pubkey = MEMBER_1_PUBKEY;
        vm.expectEmit(address(pm));
        emit IPegManager.SignatureAdded(
            pegOutTxHash, streamId, packetNumber, slotId, committeeMember1Pubkey, signature, nonce
        );

        // We emit the event we expect to see.
        vm.expectEmit(address(pm));
        emit IPegManager.AllSignaturesReady(pegOutTxHash, streamId, packetNumber, slotId);

        // Act
        address committeeMember2adr = MEMBER_1_ADDRESS;
        vm.startPrank(committeeMember2adr);
        allSignaturesReady =
            pm.addMemberSignaturePegoutTxHash(pegOutTxHash, streamId, packetNumber, slotId, signature, nonce);
        vm.stopPrank();

        // Assert
        assertEq(allSignaturesReady, true, "Not all signatures should be ready at this point");
    }

    function test_addMemberSignaturePegoutTxHash_Revert_PegOutRequestNotFound() external {
        // Arrange
        bytes32 pegOutTxHash = 0x0000000000000000000000000000000000000000000000000000000000000001;
        uint64 streamId = 0;
        uint64 packetNumber = 0;
        uint64 slotId = 0;

        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.PegOutRequestNotFound.selector, pegOutTxHash, streamId, packetNumber, slotId
            )
        );

        // Act
        pm.addMemberSignaturePegoutTxHash(pegOutTxHash, streamId, packetNumber, slotId, signature, nonce);
    }

    function test_addMemberSignaturePegoutTxHash_Revert_MemberNotFound() external {
        // This test has to perform all the steps of the pegout flow but we do not need the asserts
        // since that is already being checked
        (bytes32 pegOutTxHash, uint64 streamId, uint64 packetNumber, uint64 slotId) = helper_arrangeRequestPegout();

        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        // Assert
        address memberAddress = address(0);
        vm.expectRevert(abi.encodeWithSelector(IPegManager.MemberNotFound.selector, memberAddress));

        vm.startPrank(memberAddress);
        pm.addMemberSignaturePegoutTxHash(pegOutTxHash, streamId, packetNumber, slotId, signature, nonce);
        vm.stopPrank();
    }

    function test_addMemberSignaturePegoutTxHash_Revert_MemberHasAlreadySigned() external {
        // This test has to perform all the steps of the pegout flow but we do not need the asserts
        // since that is already being checked
        (bytes32 pegOutTxHash, uint64 streamId, uint64 packetNumber, uint64 slotId) = helper_arrangeRequestPegout();

        // Arrange
        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        // Assert that the first signature is added
        // We emit the event we expect to see.
        bytes32 committeeMember0Pubkey = MEMBER_0_PUBKEY;
        vm.expectEmit(address(pm));
        emit IPegManager.SignatureAdded(
            pegOutTxHash, streamId, packetNumber, slotId, committeeMember0Pubkey, signature, nonce
        );

        // Act
        address committeeMember0adr = MEMBER_0_ADDRESS;
        vm.startPrank(committeeMember0adr);
        bool allSignaturesReady =
            pm.addMemberSignaturePegoutTxHash(pegOutTxHash, streamId, packetNumber, slotId, signature, nonce);
        vm.stopPrank();

        // Assert
        assertEq(allSignaturesReady, false, "Not all signatures should be ready at this point");

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.MemberHasAlreadySigned.selector, committeeMember0Pubkey, committeeMember0adr, pegOutTxHash
            )
        );

        // Act sign a second time with the same committee member
        vm.startPrank(committeeMember0adr);
        allSignaturesReady =
            pm.addMemberSignaturePegoutTxHash(pegOutTxHash, streamId, packetNumber, slotId, signature, nonce);
        vm.stopPrank();
    }

    function test_addMemberSignaturePegoutTxHash_Revert_MemberNotFoundInCommittee() external {
        // This test has to perform all the steps of the pegout flow but we do not need the asserts
        // since that is already being checked
        (bytes32 pegOutTxHash, uint64 streamId, uint64 packetNumber, uint64 slotId) = helper_arrangeRequestPegout();

        // Arrange
        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        bytes32 nonCommitteeMemberPubkey = MEMBER_2_PUBKEY;

        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.MemberNotFoundInCommittee.selector, nonCommitteeMemberPubkey, pegOutTxHash
            )
        );

        // Act
        address nonCommitteeMember = MEMBER_2_ADDRESS;
        vm.startPrank(nonCommitteeMember);
        pm.addMemberSignaturePegoutTxHash(pegOutTxHash, streamId, packetNumber, slotId, signature, nonce);
        vm.stopPrank();
    }

    function test_addMemberSignaturePegoutTxHash_Revert_InvalidNonceLength() external {
        // This test has to perform all the steps of the pegout flow but we do not need the asserts
        // since that is already being checked
        (bytes32 pegOutTxHash, uint64 streamId, uint64 packetNumber, uint64 slotId) = helper_arrangeRequestPegout();

        // Arrange
        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"fff8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        address CommitteeMember = MEMBER_0_ADDRESS;

        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.InvalidNonceLength.selector, nonce.length, Constants.SIGNATURE_NONCE_LENGTH
            )
        );

        // Act
        vm.startPrank(CommitteeMember);
        pm.addMemberSignaturePegoutTxHash(pegOutTxHash, streamId, packetNumber, slotId, signature, nonce);
        vm.stopPrank();
    }

    function helper_arrangeRequestPegout() internal returns (bytes32, uint64, uint64, uint64) {
        // Arrange
        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";

        bytes32 txId = 0xb24858ade3e5be49ae63facb93524ddf460d0771f093525dae328b6c435516a2;
        bytes memory scriptPubKey = hex"02f519f51e435c20d38af683ea86862f4591ce8cda248077c2d9a72a76b62f32";

        uint64 amount = 10000000; // 0.1 BTC
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);

        Stream memory stream = streamManager.getStream(uint64(amount));
        uint64 packetNumber = 0;
        uint64 slotId = 0;

        streamManager.setSlotHarness(
            stream.streamId, packetNumber, slotId, SlotState.FILLED, scriptPubKey, txId, amount
        );

        // Execute pegout as part of the arrange
        pm.requestPegOut{value: amountInWei}(usrPubKey);
        bytes32 pegOutSignatureHash = pm.getPegOutSignatureHash(stream.streamId, packetNumber, slotId);

        return (pegOutSignatureHash, stream.streamId, packetNumber, slotId);
    }
}
