// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "forge-std/console.sol";
import {HelperContract} from "test/helpers/HelperContract.sol";
import {
    BtcTransaction,
    BtcTxSPVProof,
    StreamPosition,
    RequestPegInTempInfo,
    PegStatus,
    IPegManager
} from "src/interfaces/IPegManager.sol";
import {BtcTxIn, BtcTxOut} from "src/interfaces/IBitcoinManager.sol";
import {Slot, SlotState, Packet, Stream, IStreamManager} from "src/interfaces/IStreamManager.sol";
import {BTC_TRANSACTION_CONFIRMATION_INVALID_MERKLE_BRANCH_ERROR_CODE} from "src/interfaces/IBridge.sol";
import {ProofValidator} from "src/ProofValidator.sol";
import {BtcHelper} from "src/libraries/BtcHelper.sol";
import {Constants} from "src/libraries/Constants.sol";

// This addresses and pubkeys are the ones generated by anvil and the deploy script
bytes32 constant MEMBER_0_PUBKEY = 0xecffc8106b3c958bd88d6d30490b30363bf5adf16d35c5d31a2bd219df53ca52;
address constant MEMBER_0_ADDRESS = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
bytes32 constant MEMBER_1_PUBKEY = 0xefc3606f43ef541fff3328af5ea0a16ad9e4ae67d8d5595e8ba4ad1c00517d55;
address constant MEMBER_1_ADDRESS = 0x70997970C51812dc3A010C7d01b50e0d17dc79C8;
bytes32 constant MEMBER_2_PUBKEY = 0x1976ee2a061feb3976914ed2526369c7141b5490f48d5623485e833c2e9c5819;
address constant MEMBER_2_ADDRESS = 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC;

contract TestPegManager is Test, HelperContract {
    // Arrange
    // https://www.blockchain.com/explorer/blocks/btc/879500
    uint64 internal constant PACKET_NUMBER = 0;
    address internal constant RSK_DESTINATION_ADDRESS = 0x7Ac5496aee77c1bA1F0854206A26DdA82A81d6d8;

    function setUp() external {
        runTestDeployScript();
    }

    // ================= Request PegOut =================
    function test_requestPegOut_Success() external {
        // Arrange
        bytes32 expectedHash = 0xf48100e48109fb0e00c7d4e826b0509347f64fd2874bca28cff17d3d31e8bb9a;
        bytes memory expectedDigest =
            hex"00010200000000000000234337e863e00e6ff45f167a14f3963bea912bc0d739c2b402d04f376e814ae2e247139cedddd1ee740814e7de2e771c3745091bbb7af21d4122087c8bc17a36a0c6dbc3091625a23fd870bf8d09182484c12fa63a5c29045a431cf445f153e523e9829bfb4e23fbd3c4848baa035af15d73bcb83e510f7f097f90a21a4280d2006bb47323a1d7550c68619b10ffa4748cae2dc9f58375cfb06ae22cc8020e530000000000";

        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";

        bytes32 txId = 0xb24858ade3e5be49ae63facb93524ddf460d0771f093525dae328b6c435516a2;
        bytes memory scriptPubKey = hex"02f519f51e435c20d38af683ea86862f4591ce8cda248077c2d9a72a76b62f32";

        uint64 amount = 10000000; // 0.1 BTC
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);

        Stream memory stream = streamManager.getStream(uint64(amount));
        uint64 packetNumber = 0;
        uint64 slotId = 0;

        streamManager.setSlotHarness(stream.streamId, packetNumber, scriptPubKey, txId, amount);

        // Assert
        vm.expectEmit(address(pm));
        emit IPegManager.PegOutRequested(
            usrPubKey, amount, expectedHash, expectedDigest, stream.streamId, packetNumber, slotId
        );

        // Act
        pm.requestPegOut{value: amountInWei}(usrPubKey);

        // Assert
        bytes32 pegOutSignatureHash = pm.getPegOutSignatureHash(stream.streamId, packetNumber, slotId);
        assertEq(pegOutSignatureHash, expectedHash, "expected hash doesn't match the pegout computed one");

        // Assert
        Slot memory slot = streamManager.getSlot(stream.streamId, packetNumber, slotId);
        assertEq(uint64(slot.state), uint64(SlotState.LOCKED), "Slot was not locked");

        // Assert
        // Check if the signatures struct was initialized by checking that the function doesn't revert, we expect false since it hasn't been signed yet
        assertEq(pm.checkAllSignaturesReady(expectedHash), false, "Signatures struct hasn't been initialized");
    }

    function test_requestPegOut_fromAcceptPegIn_Success() external {
        // Setup
        setup_requestAndAcceptPeginFlow();

        // Arrange
        bytes32 expectedHash = 0x99befc0d4167efaf7e3ec5e8067a1a7c3a90ec85c1f9a792ce309b7eca630999;

        // These values are attached to txIdCounter value in HelperContract.getPegInRequestTxIn().
        // Counter should start in 0, otherwise the test will fail or expectedDigestc and usrPubKey should be updated.
        bytes memory expectedDigest =
            hex"00010200000000000000cf72c080d473fbab8c45b1c13be4215e216bb20171c0fd659632ce0779df8bc7b223ac0e009cf54402b2529ea4312214616df58c903ec7fd399c12fb08e8e675be45ad9e08ae96e42d7fd1f70a454432049ebd6a625fa377ffa22033fd8692d623e9829bfb4e23fbd3c4848baa035af15d73bcb83e510f7f097f90a21a4280d2cca26f66149c86d9940e70592f0e9c8b07b8cb01d0aabb7782c9d6b17bc12e270000000000";

        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";

        uint64 amount = VALUE;
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);

        Stream memory stream = streamManager.getStream(amount);
        uint64 slotId = stream.pegoutSlotPointer;
        uint64 packetNumber = stream.pegoutPacketPointer;

        // Assert
        vm.expectEmit(address(pm));
        emit IPegManager.PegOutRequested(
            usrPubKey, amount, expectedHash, expectedDigest, stream.streamId, packetNumber, slotId
        );

        // Act
        pm.requestPegOut{value: amountInWei}(usrPubKey);

        // Assert
        bytes32 result = pm.getPegOutSignatureHash(stream.streamId, packetNumber, slotId);
        assertEq(result, expectedHash, "expected hash doesn't match the pegout computed one");

        // Assert
        Slot memory slot = streamManager.getSlot(stream.streamId, packetNumber, slotId);
        assertEq(uint64(slot.state), uint64(SlotState.LOCKED), "Slot was not locked");
    }

    function test_requestPegOut_FromNextPacket_Success() external {
        // Setup
        uint256 pegoutAmount = Constants.SLOTS_PER_PACKET + 10;
        setup_multipleRequestAndAcceptPeginFlows(pegoutAmount);

        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";
        uint64 amount = VALUE;
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);
        uint64 packetNumberExpected = 0;
        uint64 slotIdExpected = 0;
        Stream memory stream;

        for (uint256 i = 0; i < pegoutAmount; i++) {
            if (i % Constants.SLOTS_PER_PACKET == 0 && i != 0) {
                // We are in a new packet, so we need to update the expected packet number
                packetNumberExpected++;
            }
            slotIdExpected = uint64(i % Constants.SLOTS_PER_PACKET);

            stream = streamManager.getStream(amount);
            uint64 packetNumber = stream.pegoutPacketPointer;
            uint64 slotId = stream.pegoutSlotPointer;
            assertEq(packetNumberExpected, packetNumber);
            assertEq(slotIdExpected, slotId);

            // Act
            pm.requestPegOut{value: amountInWei}(usrPubKey);

            // Assert
            Slot memory slot = streamManager.getSlot(stream.streamId, packetNumber, slotId);
            assertEq(uint64(slot.state), uint64(SlotState.LOCKED), "Slot was not locked");
        }

        stream = streamManager.getStream(amount);
        assertEq(
            pegoutAmount,
            uint256(stream.pegoutPacketPointer) * Constants.SLOTS_PER_PACKET + stream.pegoutSlotPointer,
            "Pegout amount is not correct"
        );
    }

    function test_requestPegOut_Revert_InvalidPublicKeyLength() external {
        // Arrange
        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b00";

        // Assert
        vm.expectRevert(abi.encodeWithSelector(IPegManager.InvalidPubKeyLength.selector, usrPubKey.length));

        // Act
        pm.requestPegOut(usrPubKey);
    }

    function test_requestPegOut_Revert_StreamNotFoundByDenomination() external {
        // Arrange
        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";
        uint64 amount = 5;
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);

        // Assert
        vm.expectRevert(abi.encodeWithSelector(IStreamManager.StreamNotFoundByDenomination.selector, amount));

        // Act
        pm.requestPegOut{value: amountInWei}(usrPubKey);
    }

    function test_requestPegOut_Revert_NonExistentSlot() external {
        // Arrange
        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";
        uint64 amount = 100000; // 0.1 BTC
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);

        Stream memory stream = streamManager.getStream(uint64(amount));
        uint64 packetNumber = stream.pegoutPacketPointer;

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(IStreamManager.NonExistentSlot.selector, stream.streamId, packetNumber, 0)
        );

        // Act
        pm.requestPegOut{value: amountInWei}(usrPubKey);
    }

    // we only check the revert case since the success cases are being checked in the _addMemberSignaturePegOut tests
    function test_checkAllSignaturesReady_Revert_PegOutRequestNotFound() external {
        // Arrange
        bytes32 pegOutSignatureHash = 0x0000000000000000000000000000000000000000000000000000000000000001;

        // Assert
        vm.expectRevert(abi.encodeWithSelector(IPegManager.SignatureHashNotFound.selector, pegOutSignatureHash));

        // Act
        pm.checkAllSignaturesReady(pegOutSignatureHash);
    }

    function test_addMemberSignature_Success() external {
        bytes32 pegOutSignatureHash = setup_arrangeRequestPegOut();

        // Arrange
        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        // Assert
        // We emit the event we expect to see.
        bytes32 committeeMember0Pubkey = MEMBER_0_PUBKEY;
        vm.expectEmit(address(pm));
        emit IPegManager.SignatureAdded(pegOutSignatureHash, committeeMember0Pubkey, signature, nonce);

        // Act
        address committeeMember0adr = MEMBER_0_ADDRESS;
        vm.startPrank(committeeMember0adr);
        bool allSignaturesReady = pm.addMemberSignature(pegOutSignatureHash, signature, nonce);
        vm.stopPrank();

        // Assert
        assertEq(allSignaturesReady, false, "Not all signatures should be ready at this point");

        // Assert
        // We emit the event we expect to see.
        bytes32 committeeMember1Pubkey = MEMBER_1_PUBKEY;
        vm.expectEmit(address(pm));
        emit IPegManager.SignatureAdded(pegOutSignatureHash, committeeMember1Pubkey, signature, nonce);

        // We emit the event we expect to see.
        vm.expectEmit(address(pm));
        emit IPegManager.AllSignaturesReady(pegOutSignatureHash);

        // Act
        address committeeMember2adr = MEMBER_1_ADDRESS;
        vm.startPrank(committeeMember2adr);
        allSignaturesReady = pm.addMemberSignature(pegOutSignatureHash, signature, nonce);
        vm.stopPrank();

        // Assert
        assertEq(allSignaturesReady, true, "Not all signatures should be ready at this point");
    }

    function test_addMemberSignature_Revert_PegOutRequestNotFound() external {
        // Arrange
        bytes32 pegOutSignatureHash = 0x0000000000000000000000000000000000000000000000000000000000000001;

        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        // Assert
        vm.expectRevert(abi.encodeWithSelector(IPegManager.SignatureHashNotFound.selector, pegOutSignatureHash));

        // Act
        pm.addMemberSignature(pegOutSignatureHash, signature, nonce);
    }

    function test_addMemberSignature_Revert_MemberNotFound() external {
        bytes32 pegOutSignatureHash = setup_arrangeRequestPegOut();

        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        // Assert
        address memberAddress = address(0);
        vm.expectRevert(abi.encodeWithSelector(IPegManager.MemberNotFound.selector, memberAddress));

        vm.startPrank(memberAddress);
        pm.addMemberSignature(pegOutSignatureHash, signature, nonce);
        vm.stopPrank();
    }

    function test_addMemberSignature_Revert_MemberHasAlreadySigned() external {
        bytes32 pegOutSignatureHash = setup_arrangeRequestPegOut();

        // Arrange
        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        // Assert that the first signature is added
        // We emit the event we expect to see.
        bytes32 committeeMember0Pubkey = MEMBER_0_PUBKEY;
        vm.expectEmit(address(pm));
        emit IPegManager.SignatureAdded(pegOutSignatureHash, committeeMember0Pubkey, signature, nonce);

        // Act
        address committeeMember0adr = MEMBER_0_ADDRESS;
        vm.startPrank(committeeMember0adr);
        bool allSignaturesReady = pm.addMemberSignature(pegOutSignatureHash, signature, nonce);
        vm.stopPrank();

        // Assert
        assertEq(allSignaturesReady, false, "Not all signatures should be ready at this point");

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.MemberHasAlreadySigned.selector,
                committeeMember0Pubkey,
                committeeMember0adr,
                pegOutSignatureHash
            )
        );

        // Act sign a second time with the same committee member
        vm.startPrank(committeeMember0adr);
        allSignaturesReady = pm.addMemberSignature(pegOutSignatureHash, signature, nonce);
        vm.stopPrank();
    }

    function test_addMemberSignature_Revert_MemberNotFoundInCommittee() external {
        bytes32 pegOutSignatureHash = setup_arrangeRequestPegOut();

        // Arrange
        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        bytes32 nonCommitteeMemberPubkey = MEMBER_2_PUBKEY;

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.MemberNotFoundInCommittee.selector, nonCommitteeMemberPubkey, pegOutSignatureHash
            )
        );

        // Act
        address nonCommitteeMember = MEMBER_2_ADDRESS;
        vm.startPrank(nonCommitteeMember);
        pm.addMemberSignature(pegOutSignatureHash, signature, nonce);
        vm.stopPrank();
    }

    function test_addMemberSignature_Revert_InvalidNonceLength() external {
        bytes32 pegOutSignatureHash = setup_arrangeRequestPegOut();

        // Arrange
        // The signature an nonce values are dummy values
        bytes32 signature = hex"f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0";
        bytes memory nonce =
            hex"fff8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0f8c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a00000";

        address CommitteeMember = MEMBER_0_ADDRESS;

        // Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                IPegManager.InvalidNonceLength.selector, nonce.length, Constants.SIGNATURE_NONCE_LENGTH
            )
        );

        // Act
        vm.prank(CommitteeMember);
        pm.addMemberSignature(pegOutSignatureHash, signature, nonce);
    }

    function setup_arrangeRequestPegOut() internal returns (bytes32) {
        // Arrange
        bytes memory usrPubKey = hex"02d56ad001b55eabf431e602599fcc0d7ed9d676ac93c2be11d0de6e25dd598d8b";

        bytes32 txId = 0xb24858ade3e5be49ae63facb93524ddf460d0771f093525dae328b6c435516a2;
        bytes memory scriptPubKey = hex"02f519f51e435c20d38af683ea86862f4591ce8cda248077c2d9a72a76b62f32";

        uint64 amount = 10000000; // 0.1 BTC
        uint256 amountInWei = BtcHelper.satoshiToWei(amount);

        Stream memory stream = streamManager.getStream(uint64(amount));
        uint64 packetNumber = 0;

        uint64 slotId = streamManager.setSlotHarness(stream.streamId, packetNumber, scriptPubKey, txId, amount);

        // Execute pegout as part of the arrange
        pm.requestPegOut{value: amountInWei}(usrPubKey);
        bytes32 pegOutSignatureHash = pm.getPegOutSignatureHash(stream.streamId, packetNumber, slotId);

        return (pegOutSignatureHash);
    }
}
