services:
  # Trail of bits security tools
  # We will use Slither
  # https://github.com/trailofbits/eth-security-toolbox/
  eth-security-toolbox:
    image: "ghcr.io/trailofbits/eth-security-toolbox/ci:nightly"
    platform: "linux/amd64"
    command:
      - /bin/bash
      - -c
      - |
        slither --version
        slither ./share --filter-paths "lib/" --exclude naming-convention,low-level-calls,incorrect-equality
    volumes:
      - ./:/share
