[package]
name = "bitvmx-union-bridge-contracts" # the name of the package
version = "0.1.0"    # the current version, obeying semver

[profile.default]
solc_version = "0.8.28"
# Use emv version previous to Paris in RSK to avoid prevrandao error 
# https://book.getfoundry.sh/cheatcodes/prevrandao
evm_version = "london" 
optimizer = true
optimizer_runs = 2000
ffi = true

[profile.ci.fuzz]
runs = 10_000