[profile.default]
solc_version = "0.8.28"
# Use emv version previous to Paris in RSK to avoid prevrandao error 
# https://book.getfoundry.sh/cheatcodes/prevrandao
evm_version = "london" 
optimizer = true
optimizer_runs = 2000
ffi = true
# gas limit in tests
gas_limit = 30000000

[profile.ci.fuzz]
runs = 10_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config