[profile.default]
solc_version = "0.8.30"
# Use emv version previous to Paris in RSK to avoid prevrandao error
# https://book.getfoundry.sh/cheatcodes/prevrandao
evm_version = "london"
optimizer = true
optimizer_runs = 100
block_gas_limit = 2650000000
# TODO Create2 is not compatible with OpenZeppelin upgrades
# Create2, In order to reliably deploy to deterministic addresses we will need to make sure our bytecode stays the same
# bytecode_hash = "none"
# cbor_metadata = false
# always_use_create_2_factory = true
# This is needed by foundry-upgrades
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
# Fix  call didn't revert at a lower depth than cheatcode call depth https://github.com/PaulRBerg/prb-math/issues/248
allow_internal_expect_revert = true

# Ignore gas reports for Test contracts and test infrastructure
gas_reports_ignore = [
    "ERC1967Proxy",
    "DeployScript",
    "BridgeMock",
    "HelperContract",
    "ProofValidatorHarness",
    "TestUtils",
    "TestPeginManager",
    "TestPegoutManager",
    "TestSignatureManager",
]

# Verbosity level usefull for debugging same as -vvv
verbosity = 3

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config

[lint]
exclude_lints = [
    "mixed-case-variable",
    "mixed-case-function",
    "asm-keccak256",
    "pascal-case-struct",
    "incorrect-shift",
]
