// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import {StreamDenomination, Role, CommitteeMember, Committee, CommitteeRegistry} from "src/CommitteeRegistry.sol";
import {StreamManager} from "src/StreamManager.sol";
import {TestUtils} from "test/helpers/TestUtils.sol";
import {ChainIds} from "src/libraries/Network.sol";
import {BtcHelper} from "src/libraries/BtcHelper.sol";
import {ScriptUtils} from "script/helpers/ScriptUtils.sol";

// Required amount of members to register, can be at most 10 since that is the amount of wallets generated by anvil
// At the moment we register 3 members but we add only 2 to the committee for testing purposes
uint8 constant REQUIRED_MEMBERS_AMOUNT = 3;

struct RegisterCommitteeParams {
    Committee committee;
}

struct RegisterMemberParams {
    bytes32 publicKey;
    StreamDenomination requestedStream;
    Role requestedRole;
}

contract SetUpCommittees is ScriptUtils, TestUtils {
    /// @notice parameters for each chain
    /// like https://github.com/defi-wonderland/solidity-foundry-boilerplate/blob/main/script/Deploy.sol
    RegisterCommitteeParams[] public committeesParams;
    StreamDenomination defaultRequestedStream = StreamDenomination._0_001BTC;
    Role defaultRequestedRole = Role.Watchtower;

    function setUp() internal {
        require(REQUIRED_MEMBERS_AMOUNT <= 10, "REQUIRED_MEMBERS_AMOUNT must be less than or equal to 10");

        // Map memebers to comittee
        CommitteeMember[] memory members = new CommitteeMember[](2);
        members[0] = CommitteeMember({index: 0, role: Role.Operator});
        members[1] = CommitteeMember({index: 1, role: Role.Watchtower});

        // Committee setup
        committeesParams.push();
        committeesParams[0].committee.memberIndexesAndRoles.push(members[0]);
        committeesParams[0].committee.memberIndexesAndRoles.push(members[1]);
        committeesParams[0].committee.leaderIndex = 0;

        if (block.chainid == ChainIds.RSK_MAINNET) {
            // RSK Mainnet
            committeesParams[0].committee.aggregatedKey =
                0x924c163b385af7093440184af6fd6244936d1288cbb41cc3812286d3f83a3329;
        } else if (block.chainid == ChainIds.RSK_TESTNET) {
            // RSK Testnet
            // Obtained from transactions repository
            committeesParams[0].committee.aggregatedKey =
                0xd1cfc2049322ff6ba3a88c6e17c6622308f0fb1d2910ffadb309e4116358723d;
        } else if (block.chainid == ChainIds.LOCAL) {
            // Foundry local chainid
            // Obtained from transactions repository
            committeesParams[0].committee.aggregatedKey =
                0xd1cfc2049322ff6ba3a88c6e17c6622308f0fb1d2910ffadb309e4116358723d;
        } else {
            revert("Blockchain is not RSK");
        }
    }

    function run(CommitteeRegistry _committeeRegistry) public {
        setUp();
        registerMembers(_committeeRegistry);
        registerCommittees(_committeeRegistry, committeesParams);
    }

    function registerMembers(CommitteeRegistry _committeeRegistry) public {
        for (uint32 i = 0; i < REQUIRED_MEMBERS_AMOUNT; i++) {
            registerMember(_committeeRegistry, getMemberKey(i));
        }
    }

    function registerMember(CommitteeRegistry _committeeRegistry, uint256 _privKey) public {
        // Add balance to the user
        address user = vm.addr(_privKey);
        RegisterMemberParams memory params = getMemberParams(_privKey);

        uint256 minimumDeposit = _committeeRegistry.getMinimumDeposit(params.requestedStream);

        vm.deal(user, minimumDeposit);

        vm.startBroadcast(_privKey);
        _committeeRegistry.depositBond{value: minimumDeposit}(
            params.publicKey, params.requestedStream, params.requestedRole
        );
        vm.stopBroadcast();
    }

    function registerCommittees(
        CommitteeRegistry _committeeRegistry,
        RegisterCommitteeParams[] memory _registerCommitteesParams
    ) public {
        uint256 length = _registerCommitteesParams.length;
        for (uint256 i = 0; i < length; i++) {
            Committee memory committee = _registerCommitteesParams[i].committee;
            registerCommittee(_committeeRegistry, i + 1, committee);
            _compareCommittees(_committeeRegistry.getCommittee(i + 1), committee);
        }
    }

    function _compareCommittees(Committee memory _contractCommittee, Committee memory _committee) internal pure {
        if (_contractCommittee.aggregatedKey != _committee.aggregatedKey) {
            revert("CommitteeRegistry committee registered has not the same aggregated key as the one in the contract");
        }

        if (_contractCommittee.memberIndexesAndRoles.length != _committee.memberIndexesAndRoles.length) {
            revert("CommitteeRegistry committee registered has not same member length as the one in the contract");
        }

        for (uint256 i = 0; i < _committee.memberIndexesAndRoles.length; i++) {
            if (_contractCommittee.memberIndexesAndRoles[i].index != _committee.memberIndexesAndRoles[i].index) {
                revert("CommitteeRegistry committee registered has a different index member as the one in the contract");
            }
            if (_contractCommittee.memberIndexesAndRoles[i].role != _committee.memberIndexesAndRoles[i].role) {
                revert("CommitteeRegistry committee registered has a different role member as the one in the contract");
            }
        }

        if (_contractCommittee.leaderIndex != _committee.leaderIndex) {
            revert("CommitteeRegistry committee registered has a different leaderIndex as the one in the contract");
        }
    }

    function registerCommittee(CommitteeRegistry _committeeRegistry, uint256 _committeeId, Committee memory _commitee)
        public
    {
        vm.startBroadcast(getDeployerKey());
        _committeeRegistry.registerCommittee(_committeeId, _commitee);
        vm.stopBroadcast();
    }

    function getMemberParams(uint256 _privKey) public view returns (RegisterMemberParams memory) {
        bytes32 pubKey = BtcHelper.hash256(abi.encode(_privKey));
        return RegisterMemberParams(pubKey, defaultRequestedStream, defaultRequestedRole);
    }

    function setStreamManager(CommitteeRegistry _committeeRegistry, StreamManager _streamManager) public {
        vm.startBroadcast(getDeployerKey());
        _committeeRegistry.setStreamManager(_streamManager);
        vm.stopBroadcast();
    }
}
