// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import {console} from "forge-std/console.sol";
import {DeployScript} from "script/deploy/DeployScript.s.sol";
import {PegManager, BtcTxSPVProof} from "src/PegManager.sol";
import {StreamManagerHarness} from "test/helpers/StreamManagerHarness.sol";
import {SignatureManager} from "src/SignatureManager.sol";
import {Role, Member, CommitteeMember, Committee, CommitteeRegistry} from "src/CommitteeRegistry.sol";
import {StreamDenomination} from "src/interfaces/IStreamManager.sol";
import {BtcTxIn, BtcTxOut, BtcTransaction} from "src/interfaces/IBitcoinManager.sol";
import {BitcoinManager} from "src/BitcoinManager.sol";
import {BtcScriptParser} from "src/libraries/BtcScriptParser.sol";
import {BtcHelper} from "src/libraries/BtcHelper.sol";
import {BtcTxEncoder} from "src/libraries/BtcTxEncoder.sol";
import {RSK_BRIDGE_ADDRESS, IBridge} from "src/interfaces/IBridge.sol";
import {BridgeMock} from "./BridgeMock.sol";
import {TestUtils} from "./TestUtils.sol";
import {Constants} from "src/libraries/Constants.sol";
import {OpCodes} from "src/libraries/OpCodes.sol";
import {Stream} from "src/interfaces/IStreamManager.sol";
import {CommitteeRegistryHarness} from "./CommitteeRegistryHarness.sol";

abstract contract HelperContract is Test, TestUtils {
    // This addresses and pubkeys are the ones generated by anvil and the deploy script
    bytes32 constant MEMBER_0_PUBKEY = 0xecffc8106b3c958bd88d6d30490b30363bf5adf16d35c5d31a2bd219df53ca52;
    address constant MEMBER_0_ADDRESS = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
    bytes32 constant MEMBER_1_PUBKEY = 0xefc3606f43ef541fff3328af5ea0a16ad9e4ae67d8d5595e8ba4ad1c00517d55;
    address constant MEMBER_1_ADDRESS = 0x70997970C51812dc3A010C7d01b50e0d17dc79C8;
    bytes32 constant MEMBER_2_PUBKEY = 0x1976ee2a061feb3976914ed2526369c7141b5490f48d5623485e833c2e9c5819;
    address constant MEMBER_2_ADDRESS = 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC;
    bytes32 constant MEMBER_3_PUBKEY = 0x445787646b92cfbfdbe6bdd722431134923983b24e8ce4765c4eabdf7250a42c;
    address constant MEMBER_3_ADDRESS = 0x90F79bf6EB2c4f870365E785982E1f101E93b906;

    // Mock keys
    bytes32 constant COMMITEE_1_PUB_KEY = 0xd1cfc2049322ff6ba3a88c6e17c6622308f0fb1d2910ffadb309e4116358723d;
    uint256 constant COMMITTEE_1_ID = 1;
    bytes32 constant COMMITEE_2_PUB_KEY = 0x1908421cb37d204b0c68660d093534d50d01fa791a3313e5fd9c21da137785ec;
    uint256 constant COMMITTEE_2_ID = 2;
    bytes32 constant COMMITEE_3_PUB_KEY = 0x2908421cb37d204b0c68660d093534d50d01fa791a3313e5fd9c21da137785ed;
    uint256 constant COMMITTEE_3_ID = 3;
    bytes32 internal constant BTC_REIMBURSEMENT_PUBKEY =
        0x7d235c24420b2f55450c8414725aa74e6db01035245efdab0e1cfa7ab29aca0f;

    // Dummy requested roles and streams for the members
    StreamDenomination internal constant DEFAULT_STREAM = StreamDenomination._0_001BTC;
    Role internal constant DEFAULT_ROLE = Role.Operator;

    BitcoinManager internal bitcoinManager;
    CommitteeRegistryHarness internal registry;

    Committee internal committee1;
    Committee internal committee2;
    Committee internal committee3;

    CommitteeMember[] internal committee1Members;
    CommitteeMember[] internal committee2Members;
    CommitteeMember[] internal committee3Members;

    PegManager internal pm;
    StreamManagerHarness internal streamManager;
    BridgeMock internal bridgeMock;
    SignatureManager internal signatureManager;
    address upgradeOwner = vm.addr(777);
    // Arrange
    uint64 internal constant VALUE = 1_000_000; // 0.01 BTC

    function setup_committeeMembers(uint256 numWatchtowers, uint256 numOperators, StreamDenomination denomination)
        internal
    {
        uint256 totalMembers = numWatchtowers + numOperators;

        for (uint256 memberIndex = 1; memberIndex <= totalMembers; memberIndex++) {
            bytes32 pubKey = generatePubKey(memberIndex);
            uint256 minimumDeposit = registry.getMinimumDeposit(denomination);
            address user = vm.addr(memberIndex); // Use a different address for each member
            vm.deal(user, minimumDeposit);

            // First numWatchtowers members are watchtowers, the rest are operators
            Role role = memberIndex <= numWatchtowers ? Role.Watchtower : Role.Operator;

            // Register member in the registry using unique address
            vm.prank(user); // Use a different address for each member
            registry.depositBond{value: minimumDeposit}(pubKey, denomination, role);
        }
    }

    function setUpCommittees() internal {
        committee1Members.push(CommitteeMember({index: 0, role: Role.Operator}));
        committee1Members.push(CommitteeMember({index: 1, role: Role.Watchtower}));

        committee2Members.push(CommitteeMember({index: 1, role: Role.Operator}));
        committee2Members.push(CommitteeMember({index: 2, role: Role.Operator}));

        committee3Members.push(CommitteeMember({index: 0, role: Role.Operator}));
        committee3Members.push(CommitteeMember({index: 2, role: Role.Operator}));

        committee1.aggregatedKey = COMMITEE_1_PUB_KEY;
        committee1.memberIndexesAndRoles = committee1Members;
        committee1.leaderIndex = 0;

        committee2.aggregatedKey = COMMITEE_2_PUB_KEY;
        committee2.memberIndexesAndRoles = committee2Members;
        committee2.leaderIndex = 0;

        committee3.aggregatedKey = COMMITEE_3_PUB_KEY;
        committee3.memberIndexesAndRoles = committee3Members;
        committee3.leaderIndex = 0;
    }

    function runTestDeployScript() internal {
        // Using the deployment script in tests like in
        // https://github.com/Cyfrin/foundry-smart-contract-lottery-cu/blob/main/test/unit/RaffleTest.t.sol#L38
        DeployScript deployScript = new DeployScript();
        deployScript.run();
        bitcoinManager = deployScript.bitcoinManager();
        registry = CommitteeRegistryHarness(address(deployScript.committeeRegistry()));
        pm = deployScript.pegManager();
        streamManager = StreamManagerHarness(address(deployScript.streamManager()));
        // Set up bridge mock at bridge precompiled address
        bridgeMock = BridgeMock(deployScript.bridgeAddress());
        signatureManager = SignatureManager(deployScript.signatureManager());
        // Register committees with their mock keys. These are Bitcoin x-only public keys.
        setUpCommittees();
    }

    // ========================== Peg In Request ==========================
    // This counter is added to the txId from getPegInRequestTxIn to avoid collisions when doing multiple pegin's
    uint256 internal txIdCounter = 0;

    function getPegInRequestTxIn() internal returns (BtcTxIn memory) {
        return BtcTxIn({
            txId: bytes32(uint256(0x360b81785dc7c2f40627fea364676dbb73e6276683caffd9f906b0e0bd36b3d2) + txIdCounter++),
            vout: 1694,
            sequence: Constants.SEQUENCE,
            scriptSig: hex""
        });
    }

    function getPegInRequestP2TROut() internal pure returns (BtcTxOut memory) {
        return BtcTxOut({
            amount: VALUE,
            // TODO this is the value that includes the op_return data inside the taptree
            // It should be put back once the protocol builder is updated
            // scriptPubKey: hex"5120c8c2100e84799661079100ee50ce96bd1db6a1021819042b5b950ef01a4e7f41"
            scriptPubKey: hex"5120228f281f297fd01cd363b9c93f742ba2976c1ec5a6083d9f754cb61e505356c3"
        });
    }

    function getPegInRequestPacket() internal pure returns (uint64) {
        return 0;
    }

    function getPegInRskDestinationAddress() internal pure returns (address) {
        return 0x7Ac5496aee77c1bA1F0854206A26DdA82A81d6d8;
    }

    function getPegInBtcReimbursementPubKey() internal pure returns (bytes32) {
        return 0x7d235c24420b2f55450c8414725aa74e6db01035245efdab0e1cfa7ab29aca0f;
    }

    function getPegInRequestOpReturnOut(
        uint64 _packetNumber,
        address _rskDestinationAddress,
        bytes32 _btcReimbursementPubKey
    ) internal pure returns (BtcTxOut memory) {
        bytes memory script = abi.encodePacked(
            OpCodes.OP_RETURN, // (1 byte)
            OpCodes.OP_PUSHBYTES_69, // (1 byte)
            "RSK_PEGIN", // (9 bytes)
            _packetNumber, // (8 bytes)
            _rskDestinationAddress, // (20 bytes)
            _btcReimbursementPubKey // (32 bytes)
        );

        // Return the constructed output
        return BtcTxOut({amount: 0, scriptPubKey: script});
    }

    function getBtcPegInRequestTx() internal returns (BtcTransaction memory) {
        BtcTxIn[] memory btcInputs = new BtcTxIn[](1);
        btcInputs[0] = getPegInRequestTxIn();
        // Output
        BtcTxOut[] memory btcOutputs = new BtcTxOut[](2);
        btcOutputs[0] = getPegInRequestP2TROut();

        Stream memory stream = streamManager.getStream(VALUE);
        uint64 packetNumber = stream.peginPacketPointer;

        address rskDestinationAddress = getPegInRskDestinationAddress();
        bytes32 btcReimbursementPubKey = getPegInBtcReimbursementPubKey();
        btcOutputs[1] = getPegInRequestOpReturnOut(packetNumber, rskDestinationAddress, btcReimbursementPubKey);
        return BtcTransaction({
            version: Constants.BTC_TX_VERSION,
            inputs: btcInputs,
            outputs: btcOutputs,
            locktime: Constants.LOCKTIME
        });
    }

    function getBtcTxHash(BtcTransaction memory _tx) internal pure returns (bytes32) {
        return BtcHelper.hash256(BtcTxEncoder.encodeTx(_tx));
    }

    // ========================== Peg In Accept ==========================
    function getBtcAcceptPegInTx(BtcTransaction memory _tx) internal pure returns (BtcTransaction memory) {
        BtcTxIn[] memory btcInputs = new BtcTxIn[](1);
        btcInputs[0] = getAcceptPegInTxIn(_tx);
        // Output
        BtcTxOut[] memory btcOutputs = new BtcTxOut[](2);
        btcOutputs[0] = getAcceptPegInP2TROut();
        btcOutputs[1] = getBtcSpeedUpOut();
        // Locktime
        return BtcTransaction({
            version: Constants.BTC_TX_VERSION,
            inputs: btcInputs,
            outputs: btcOutputs,
            locktime: Constants.LOCKTIME
        });
    }

    function getAcceptPegInTxIn(BtcTransaction memory _tx) internal pure returns (BtcTxIn memory) {
        return BtcTxIn({txId: getBtcTxHash(_tx), vout: 0, sequence: Constants.SEQUENCE, scriptSig: hex""});
    }

    function getBtcSpeedUpOut() internal pure returns (BtcTxOut memory) {
        return BtcTxOut({
            amount: Constants.SPEED_UP_AMOUNT,
            // TODO we consider the btc reimbursement public key as even
            // this may not be the case in the future and we should change this
            scriptPubKey: BtcScriptParser.getP2WPKHScript(abi.encodePacked(uint8(0x02), BTC_REIMBURSEMENT_PUBKEY))
        });
    }

    function getAcceptPegInP2TROut() internal pure returns (BtcTxOut memory) {
        return BtcTxOut({
            amount: VALUE - (Constants.P2TR_FEE + Constants.SPEED_UP_AMOUNT),
            scriptPubKey: hex"51209687ca13c4fb3fa3ba05c2f9119dda026bfe66f0098dcf9b896a98ecb2e96702"
        });
    }

    function satoshiToWei(uint256 _amount) internal pure returns (uint256) {
        return _amount * 10 ** 10;
    }

    function createBtcTxSPVProof(BtcTransaction memory _btcTransaction) internal pure returns (BtcTxSPVProof memory) {
        BtcTxSPVProof memory btcTxSPVProof = BtcTxSPVProof({
            blockHash: 0x0000000000000000000282fa21665766e58eb6cb94e458c3ef6d4af1121e38d9,
            btcTx: _btcTransaction,
            //values obtained from https://github.com/FairgateLabs/rust-bitvmx-transactions/blob/main/src/bin/bridge-pmt.rs
            merkleBranchPath: 949,
            merkleBranchHashes: new bytes32[](1)
        });
        btcTxSPVProof.merkleBranchHashes[0] = 0x480fd40f2e47eeea8edeef2f7f3e2c680642f748c989ed2e542fe5d28164da51;
        return btcTxSPVProof;
    }

    function setup_multipleRequestAndAcceptPeginFlows(uint256 _numberOfPegIns, uint64 _streamId) internal {
        for (uint256 i = 0; i < _numberOfPegIns; i++) {
            BtcTransaction memory btcTx = setup_requestPeginFlow();
            setup_acceptPeginFlow(btcTx);

            if (
                _numberOfPegIns > Constants.SLOTS_PER_PACKET
                    && (i % Constants.SLOTS_PER_PACKET) == Constants.SLOT_USAGE_THRESHOLD
            ) {
                setup_depositMemberInfo_MultipleMembers(_streamId, 0, registry.MIN_COMMITTEE_MEMBERS() - 1);
            }
        }
    }

    function setup_acceptPeginFlow(BtcTransaction memory _tx) public {
        // Arrange
        BtcTransaction memory btcTransaction = getBtcAcceptPegInTx(_tx);
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn accepted tx struct information
        BtcTxSPVProof memory pegInAcceptedTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Act
        pm.acceptPegInRequest(pegInAcceptedTxSPVProof);
    }

    function setup_requestPeginFlow() public returns (BtcTransaction memory) {
        // Arrange
        BtcTransaction memory btcTransaction = getBtcPegInRequestTx();
        // Set Mock Bridge state
        bridgeMock.setBtcTransactionConfirmations(10);
        // Create PegIn struct information
        BtcTxSPVProof memory pegInRequestTxSPVProof = createBtcTxSPVProof(btcTransaction);

        // Act
        pm.registerPegInRequest(pegInRequestTxSPVProof);
        return btcTransaction;
    }

    function setup_requestAndAcceptPeginFlow() public {
        BtcTransaction memory peginTx = setup_requestPeginFlow();
        setup_acceptPeginFlow(peginTx);
    }

    function setup_depositMemberInfo(uint64 _streamId, address _memberAddress) internal {
        vm.prank(_memberAddress);
        registry.depositMemberInfoForCommittee(_streamId, COMMITEE_1_PUB_KEY);
    }

    // This function is used to deposit member info for multiple members in a committee
    // Include last member in the range
    function setup_depositMemberInfo_MultipleMembers(
        uint64 _streamId,
        uint256 _memberIndexInit,
        uint256 _memberIndexEnd
    ) internal {
        for (uint256 i = _memberIndexInit; i <= _memberIndexEnd; i++) {
            // Member address is vm.address(memberIndex + 1);
            setup_depositMemberInfo(_streamId, vm.addr(i + 1));
        }
    }

    function setup_committee() internal returns (Committee memory expectedCommittee, uint64 streamId) {
        StreamDenomination denomination = StreamDenomination._0_01BTC;
        streamId = 1;
        setup_committeeMembers(registry.MIN_COMMITTEE_MEMBERS() / 2, registry.MIN_COMMITTEE_MEMBERS() / 2, denomination);
        vm.warp(1000);
        return (setup_expectedRandomCommittee(), streamId);
    }

    function setup_createCommittee() internal returns (Committee memory expectedCommittee, uint64 streamId) {
        (expectedCommittee, streamId) = setup_committee();

        vm.prank(address(pm));
        registry.createCommittee(streamId);
    }

    function setup_expectedRandomCommittee() internal view returns (Committee memory) {
        // NOTE: This function is tied to the initial setup of members that it's just 3 members
        Committee memory committee = Committee({
            aggregatedKey: bytes32(0),
            memberIndexesAndRoles: new CommitteeMember[](registry.MIN_COMMITTEE_MEMBERS()),
            leaderIndex: 0
        });

        committee.memberIndexesAndRoles[0] = CommitteeMember({index: 10, role: Role.Operator});
        committee.memberIndexesAndRoles[1] = CommitteeMember({index: 9, role: Role.Operator});
        committee.memberIndexesAndRoles[2] = CommitteeMember({index: 11, role: Role.Operator});
        committee.memberIndexesAndRoles[3] = CommitteeMember({index: 12, role: Role.Operator});
        committee.memberIndexesAndRoles[4] = CommitteeMember({index: 8, role: Role.Operator});
        committee.memberIndexesAndRoles[5] = CommitteeMember({index: 5, role: Role.Watchtower});
        committee.memberIndexesAndRoles[6] = CommitteeMember({index: 4, role: Role.Watchtower});
        committee.memberIndexesAndRoles[7] = CommitteeMember({index: 6, role: Role.Watchtower});
        committee.memberIndexesAndRoles[8] = CommitteeMember({index: 7, role: Role.Watchtower});
        committee.memberIndexesAndRoles[9] = CommitteeMember({index: 3, role: Role.Watchtower});

        return committee;
    }

    function setup_registerMember(uint256 privKey) internal {
        bytes32 pubKey = generatePubKey(privKey);
        address user = vm.addr(privKey);

        vm.prank(user);
        registry.registerMember(pubKey);
    }
}
