name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci
  IS_TEST: true

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.3.1

      - name: Run tests
        run: forge test -vvv

      - name: Start Anvil
        run: anvil --port 8545 --silent &

      - name: Simulate deployment
        run: bash shell/script/deploy/simulate-deploy.sh

      - name: Deploy contracts
        run: bash shell/script/deploy/deploy-local.sh

      - name: Fund BridgeMock
        run: bash shell/script/fund-bridge.sh

      - name: Run peg-flow
        run: bash shell/script/integration-test/peg-flow.sh

      - name: Run user-reimbursement-flow
        run: bash shell/script/integration-test/user-reimbursement-flow.sh
